In [5]:
from pathlib import Path
import pandas as pd
import json
import numpy as np

# Updated to point to the correct Google Drive path
DATA_DIR = Path("/content/drive/MyDrive/ingredia_backup/ingredia_data")
INCIDB_DIR = DATA_DIR / "incidb"

print("Data directory exists:", DATA_DIR.exists())
print("INCIDB directory exists:", INCIDB_DIR.exists())

for path in DATA_DIR.rglob("*"):
    if path.is_file():
        print(path.name, "-", round(path.stat().st_size / 1024, 2), "KB")

Data directory exists: True
INCIDB directory exists: True
open_beauty_facts_products.csv - 142.59 KB
cureskin_ingredient_flags.csv - 141.16 KB
california_chemicals_in_cosmetics.csv - 29681.46 KB
pubmed_ingredient_research.csv - 88.21 KB
ingredient_name_map.csv - 106.97 KB
fragrance_allergens.parquet - 15.85 KB
products.parquet - 57.62 KB
product_ingredients.parquet - 15.72 KB
fragrance_allergens.csv - 16.09 KB
ingredient_name_map.parquet - 52.23 KB
regulatory_status.parquet - 31.86 KB
ingredients.parquet - 100.35 KB
product_ingredients.csv - 59.21 KB
brands.parquet - 4.68 KB
regulatory_status.csv - 90.35 KB
ingredients.csv - 219.45 KB
brands.csv - 2.75 KB
products.csv - 99.9 KB

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
from pathlib import Path

# Search for any directory named 'ingredia_data' within Google Drive
drive_path = Path('/content/drive/MyDrive')
found_paths = list(drive_path.rglob('ingredia_data'))

if found_paths:
    print("Found ingredia_data folder(s) at:")
    for path in found_paths:
        print(path)
else:
    print("Could not find 'ingredia_data' automatically. Listing top-level Drive folders to help locate it:")
    for item in drive_path.iterdir():
        if item.is_dir() and not item.name.startswith('.'):
            print(" - ", item.name)

Found ingredia_data folder(s) at:
/content/drive/MyDrive/ingredia_backup/ingredia_data

In [6]:
files_to_check = [
    DATA_DIR / "open_beauty_facts_products.csv",
    DATA_DIR / "cureskin_ingredient_flags.csv",
    DATA_DIR / "california_chemicals_in_cosmetics.csv",
    DATA_DIR / "pubmed_ingredient_research.csv",
]

for path in files_to_check:
    print("\n" + "=" * 70)
    print("FILE:", path.name)

    if path.exists():
        data = pd.read_csv(path, low_memory=False)

        print("Shape:", data.shape)
        print("Columns:", data.columns.tolist())
        print("\nMissing values:")
        print(data.isna().sum().sort_values(ascending=False).head(10))
        display(data.head(3))
    else:
        print("File not found.")

======================================================================
FILE: open_beauty_facts_products.csv
Shape: (300, 11)
Columns: ['code', 'countries', 'last_modified_t', 'search_term', 'image_url', 'allergens_tags', 'brands', 'categories', 'ingredients_text', 'product_name', 'ingredients_tags']

Missing values:
categories          248
ingredients_text    217
ingredients_tags    217
allergens_tags      208
brands              188
product_name         69
image_url            65
last_modified_t       0
countries             0
code                  0
dtype: int64

,code,countries,last_modified_t,search_term,image_url,allergens_tags,brands,categories,ingredients_text,product_name,ingredients_tags
0,0015034519916,Poland,1792870351,moisturizer,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9441720461824,Morocco,1792870252,moisturizer,https://images.openbeautyfacts.org/images/prod...,NaN,NaN,NaN,NaN,NaN,NaN
2,40899329,"Finland, Ireland, Spain",1792870094,moisturizer,https://images.openbeautyfacts.org/images/prod...,[],Dentalux,NaN,NaN,Dental tape,NaN

======================================================================
FILE: cureskin_ingredient_flags.csv
Shape: (1448, 11)
Columns: ['inci_name', 'display_name', 'function', 'is_active', 'fa_trigger', 'comedogenic', 'fragrance', 'eu_allergen', 'alcohol_type', 'pregnancy_caution', 'product_count']

Missing values:
comedogenic          1402
alcohol_type         1386
fa_trigger            205
function                0
display_name            0
inci_name               0
is_active               0
fragrance               0
eu_allergen             0
pregnancy_caution       0
dtype: int64

,inci_name,display_name,function,is_active,fa_trigger,comedogenic,fragrance,eu_allergen,alcohol_type,pregnancy_caution,product_count
0,aqua,Aqua,Solvent / vehicle,0,0.0,NaN,0,0,NaN,0,1204
1,niacinamide,Niacinamide,Cell-communicating / barrier-repair active,1,0.0,0.0,0,0,NaN,0,1153
2,glycerin,Glycerin,Humectant,0,0.0,0.0,0,0,NaN,0,2141

======================================================================
FILE: california_chemicals_in_cosmetics.csv
Shape: (114635, 22)
Columns: ['CDPHId', 'ProductName', 'CSFId', 'CSF', 'CompanyId', 'CompanyName', 'BrandName', 'PrimaryCategoryId', 'PrimaryCategory', 'SubCategoryId', 'SubCategory', 'CasId', 'CasNumber', 'ChemicalId', 'ChemicalName', 'InitialDateReported', 'MostRecentDateReported', 'DiscontinuedDate', 'ChemicalCreatedAt', 'ChemicalUpdatedAt', 'ChemicalDateRemoved', 'ChemicalCount']

Missing values:
ChemicalDateRemoved    111650
DiscontinuedDate       101715
CSF                     34398
CSFId                   33973
CasNumber                6476
BrandName                 227
CompanyName                 0
CompanyId                   0
CDPHId                      0
ProductName                 0
dtype: int64

,CDPHId,ProductName,CSFId,CSF,CompanyId,CompanyName,BrandName,PrimaryCategoryId,PrimaryCategory,SubCategoryId,...,CasNumber,ChemicalId,ChemicalName,InitialDateReported,MostRecentDateReported,DiscontinuedDate,ChemicalCreatedAt,ChemicalUpdatedAt,ChemicalDateRemoved,ChemicalCount
0,2,ULTRA COLOR RICH EXTRA PLUMP LIPSTICK-ALL SHADES,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),53,...,13463-67-7,6,Titanium dioxide,06/17/2009,08/28/2013,02/01/2011,07/09/2009,07/09/2009,NaN,1
1,3,Glover's Medicated Shampoo,NaN,NaN,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,...,65996-92-1,4,Distillates (coal tar),07/01/2009,07/01/2009,NaN,07/01/2009,07/01/2009,NaN,2
2,3,Glover's Medicated Shampoo,NaN,NaN,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,...,140-67-0,5,Estragole,07/01/2009,07/01/2009,NaN,07/02/2009,07/02/2009,NaN,2

======================================================================
FILE: pubmed_ingredient_research.csv
Shape: (100, 4)
Columns: ['pmid', 'title', 'abstract', 'url']

Missing values:
abstract    26
title        1
pmid         0
url          0
dtype: int64

,pmid,title,abstract,url
0,31757238,Allergic Contact Dermatitis.,"Allergic contact dermatitis is common, resulti...",https://pubmed.ncbi.nlm.nih.gov/31757238/
1,35433115,Irritant Contact Dermatitis - a Review.,Irritant contact dermatitis is the most common...,https://pubmed.ncbi.nlm.nih.gov/35433115/
2,37061220,TFOS Lifestyle: Impact of cosmetics on the ocu...,In this report the use of eye cosmetic product...,https://pubmed.ncbi.nlm.nih.gov/37061220/

In [7]:
for filename in [
    "ingredients.csv",
    "products.csv",
    "product_ingredients.csv",
    "ingredient_name_map.csv",
    "regulatory_status.csv",
]:
    path = INCIDB_DIR / filename

    print("\n" + "=" * 70)
    print(filename)

    if path.exists():
        data = pd.read_csv(path, sep="|", dtype=str, low_memory=False)

        print("Shape:", data.shape)
        print("Columns:", data.columns.tolist())
        display(data.head(3))
    else:
        print("File not found at this path.")

======================================================================
ingredients.csv
Shape: (1123, 20)
Columns: ['ingredient_id', 'inci_name', 'cosing_matched', 'cosing_ref_no', 'cas_number', 'ec_number', 'functions', 'chemical_description', 'cosing_restriction', 'cosing_update_date', 'annex_ii', 'annex_iii', 'annex_iv', 'annex_v', 'annex_vi', 'is_common_allergen', 'allergen_source', 'comedogenic_rating', 'is_fungal_acne_trigger', 'rating_source']

,ingredient_id,inci_name,cosing_matched,cosing_ref_no,cas_number,ec_number,functions,chemical_description,cosing_restriction,cosing_update_date,annex_ii,annex_iii,annex_iv,annex_v,annex_vi,is_common_allergen,allergen_source,comedogenic_rating,is_fungal_acne_trigger,rating_source
0,51,( /-),0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
1,203,(F.I.L B38252/3),0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
2,204,(F.I.L B48924/1),0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN

======================================================================
products.csv
Shape: (200, 7)
Columns: ['product_id', 'brand_id', 'barcode_ean', 'name', 'obf_categories_tags', 'raw_ingredient_text', 'created_at']

,product_id,brand_id,barcode_ean,name,obf_categories_tags,raw_ingredient_text,created_at
0,498,467,3014284027445,Fixation extra forte,fr:cremes-adhesives-pour-protheses-dentaires,"Calcium/Zinc PVM/MA Copolymer, Paraffinum liqu...",2026-10-10 10:34:33
1,580,529,3140100336979,Shampooing expert anti pelliculaire Citrus,en:hair;en:shampoos;en:anti-dandruff-shampoos,"AQUA/WATER/EAU, SODIUM LAURETH SULFATE, SODIUM...",2026-10-10 10:34:34
2,646,583,3178041308939,Kératine Color 4.6 Châtain Chocolat,en:hair;en:hair-dyes,"Crème Colorante : Aqua, Propylene Glycol, Cety...",2026-10-10 10:34:34

======================================================================
product_ingredients.csv
Shape: (4089, 4)
Columns: ['product_id', 'ingredient_id', 'position_index', 'concentration_percentage']

  product_id ingredient_id position_index concentration_percentage
0        498          8993              1                      NaN
1        498         31648              2                      NaN
2        498         33128              3                      NaN

======================================================================
ingredient_name_map.csv
Shape: (1467, 7)
Columns: ['raw_name', 'canonical_name', 'method', 'confidence', 'ingredient_id', 'part_index', 'split_rule']

,raw_name,canonical_name,method,confidence,ingredient_id,part_index,split_rule
0,TOCOPHEROL. MAY CONTAIN (+/-): CI 77891,( /-),unresolved_residual,0.0,51,2,colon+period
1,PARFUM / FRAGRANCE. (F.I.L B38252/3),(F.I.L B38252/3),unresolved_residual,0.0,203,2,period
2,PARFUM / FRAGRANCE. (F.I.L B48924/1),(F.I.L B48924/1),unresolved_residual,0.0,204,2,period

======================================================================
regulatory_status.csv
Shape: (195, 15)
Columns: ['ingredient_id', 'inci_name', 'cas', 'jurisdiction', 'list_ref', 'status', 'instrument', 'product_type', 'max_concentration', 'condition_text', 'effective_date', 'match_method', 'source_url', 'retrieved_at', 'source_update_date']

,ingredient_id,inci_name,cas,jurisdiction,list_ref,status,instrument,product_type,max_concentration,condition_text,effective_date,match_method,source_url,retrieved_at,source_update_date
0,842,1-NAPHTHOL,90-15-3,EU,Annex III/16,RESTRICTED,(EC) 2013/344,Hair dye substance in oxidative hair dye products,NaN,After mixing under oxidative conditions the ma...,NaN,NAME,https://api.tech.ec.europa.eu/cosing20/1.0/api...,2026-10-10,14/05/2013
1,842,1-NAPHTHOL,90-15-3,EU,Annex III/16,RESTRICTED,(EU) 2013/658,Hair dye substance in oxidative hair dye products,NaN,After mixing under oxidative conditions the ma...,NaN,NAME,https://api.tech.ec.europa.eu/cosing20/1.0/api...,2026-10-10,09/09/2013
2,1489,"2,4-DIAMINOPHENOXYETHANOL HCL",66422-95-5,EU,Annex III/242,RESTRICTED,(EC) 2013/1197,(a) Hair dye substance in oxidative hair dye p...,NaN,For (a) and (b): After mixing under oxidative ...,NaN,NAME,https://api.tech.ec.europa.eu/cosing20/1.0/api...,2026-10-10,14/02/2014

In [9]:
from pathlib import Path
import pandas as pd
import numpy as np
import re
import json

# Corrected the path to include /ingredia_data
DATA_DIR = Path("/content/drive/MyDrive/ingredia_backup/ingredia_data")
INCIDB_DIR = DATA_DIR / "incidb"

ingredients = pd.read_csv(
    INCIDB_DIR / "ingredients.csv",
    sep="|",
    dtype=str,
    low_memory=False
)

products = pd.read_csv(
    INCIDB_DIR / "products.csv",
    sep="|",
    dtype=str,
    low_memory=False
)

product_ingredients = pd.read_csv(
    INCIDB_DIR / "product_ingredients.csv",
    sep="|",
    dtype=str,
    low_memory=False
)

name_map = pd.read_csv(
    INCIDB_DIR / "ingredient_name_map.csv",
    sep="|",
    dtype=str,
    low_memory=False
)

cureskin = pd.read_csv(
    DATA_DIR / "cureskin_ingredient_flags.csv",
    low_memory=False
)

print("Loaded all five datasets successfully.")

Loaded all five datasets successfully.

In [10]:
ingredient_ids = set(
    ingredients["ingredient_id"].dropna().astype(str).str.strip()
)

product_ids = set(
    products["product_id"].dropna().astype(str).str.strip()
)

mapping_ingredient_ids = set(
    product_ingredients["ingredient_id"].dropna().astype(str).str.strip()
)

mapping_product_ids = set(
    product_ingredients["product_id"].dropna().astype(str).str.strip()
)

print("Ingredient IDs:", len(ingredient_ids))
print("Product IDs:", len(product_ids))

print(
    "Product-ingredient rows with valid ingredient IDs:",
    product_ingredients["ingredient_id"].isin(ingredient_ids).sum(),
    "/",
    len(product_ingredients)
)

print(
    "Product-ingredient rows with valid product IDs:",
    product_ingredients["product_id"].isin(product_ids).sum(),
    "/",
    len(product_ingredients)
)

print(
    "Name-map ingredient IDs matching ingredient table:",
    name_map["ingredient_id"].isin(ingredient_ids).sum(),
    "/",
    name_map["ingredient_id"].notna().sum()
)

print("\nExample unmatched ingredient IDs:")
print(sorted(mapping_ingredient_ids - ingredient_ids)[:20])

Ingredient IDs: 1123
Product IDs: 200
Product-ingredient rows with valid ingredient IDs: 4089 / 4089
Product-ingredient rows with valid product IDs: 4089 / 4089
Name-map ingredient IDs matching ingredient table: 1467 / 1467

Example unmatched ingredient IDs:
[]

In [11]:
name_map["confidence_num"] = pd.to_numeric(
    name_map["confidence"], errors="coerce"
)

name_map["canonical_name"] = (
    name_map["canonical_name"]
    .fillna("")
    .astype(str)
    .str.strip()
)

print("Total mappings:", len(name_map))
print("\nMapping methods:")
print(name_map["method"].value_counts(dropna=False))

print("\nConfidence distribution:")
display(name_map["confidence_num"].describe())

print("\nUnresolved or empty canonical names:")
unresolved = name_map[
    name_map["canonical_name"].eq("")
    | name_map["method"].fillna("").str.contains(
        "unresolved", case=False
    )
]

display(unresolved.head(20))
print("Unresolved rows:", len(unresolved))

Total mappings: 1467

Mapping methods:
method
exact                  916
unresolved             164
paren_stripped         116
cleaned                108
split                   68
unresolved_residual     46
slash_variant           30
synonym_map             10
slash_same_cas           8
typo_map                 1
Name: count, dtype: int64

Confidence distribution:

count    1467.000000
mean        0.822836
std         0.342917
min         0.000000
25%         0.850000
50%         1.000000
75%         1.000000
max         1.000000
Name: confidence_num, dtype: float64

Unresolved or empty canonical names:

,raw_name,canonical_name,method,confidence,ingredient_id,part_index,split_rule,confidence_num
0,TOCOPHEROL. MAY CONTAIN (+/-): CI 77891,( /-),unresolved_residual,0.0,51,2,colon+period,0.0
1,PARFUM / FRAGRANCE. (F.I.L B38252/3),(F.I.L B38252/3),unresolved_residual,0.0,203,2,period,0.0
2,PARFUM / FRAGRANCE. (F.I.L B48924/1),(F.I.L B48924/1),unresolved_residual,0.0,204,2,period,0.0
3,PARFUM/FRAGRANCE. (F.I.L. Y70037597/1),"(F.I.L,Y70037597/1)",unresolved_residual,0.0,347,2,period,0.0
4,PARFUM/FRAGRANCE. (F.I.L.Z70042467/1),(F.I.L.Z70042467/1),unresolved_residual,0.0,407,2,period,0.0
5,(F01),(F01),unresolved,0.0,420,1,NaN,0.0
6,PARFUM / FRAGRANCE. (FIL B44107/1),(FIL B44107/1),unresolved_residual,0.0,435,2,period,0.0
7,ALCOHOL DENAT. (SD ALCOHOL 39-C),(SD ALCOHOL 39-C),unresolved_residual,0.0,550,2,period,0.0
12,12M BEIERSDOCF OUY HI,12M BEIERSDOCF OUY HI,unresolved,0.0,1286,1,NaN,0.0
21,695126 41 INGREDIENTS : AQUA / WATER,695126 41 INGREDIENTS,unresolved_residual,0.0,2291,1,colon,0.0
22,737201 6 - INGREDIENTS : AQUA / WATER,737201 6 - INGREDIENTS,unresolved_residual,0.0,2342,1,colon,0.0
23,8855963-INGREDIENTS: AQUA/WATER,8855963-INGREDIENTS,unresolved_residual,0.0,2493,1,colon,0.0
25,ACETYL ALCOHOL,ACETYL ALCOHOL,unresolved,0.0,2886,1,NaN,0.0
32,ACRYLATE/C10-30 ALKYL ACRYLATE CROSSPOLYMER,ACRYLATE/C10-30 ALKYL ACRYLATE CROSSPOLYMER,unresolved,0.0,3136,1,NaN,0.0
42,1-NAPHTHOL. ACTIVATOR AQUA/WATER/EAU,ACTIVATOR AQUA/WATER/EAU,unresolved_residual,0.0,3315,2,period,0.0
59,ALLANTON COCAMIDOPROPYL BETAINE,ALLANTON COCAMIDOPROPYL BETAINE,unresolved,0.0,3975,1,NaN,0.0
71,ALPHA-ISOMETHYL LONONE,ALPHA-ISOMETHYL LONONE,unresolved,0.0,4303,1,NaN,0.0
75,ALUMINIUM CHLOROHYDRATE,ALUMINIUM CHLOROHYDRATE,unresolved,0.0,4407,1,NaN,0.0
76,ALUMINIUM ZIRCONIUM TETRACHLOROHYDREX GLY,ALUMINIUM ZIRCONIUM TETRACHLOROHYDREX GLY,unresolved,0.0,4422,1,NaN,0.0
84,AMARA (BITTER ORANGE) FLOWER OIL,AMARA (BITTER ORANGE) FLOWER OIL,unresolved,0.0,4508,1,NaN,0.0

Unresolved rows: 210

In [12]:
def normalize_name(value):
    if pd.isna(value):
        return ""
    value = str(value).casefold().strip()
    value = re.sub(r"\s+", " ", value)
    return value

ingredients["normalized_name"] = ingredients["inci_name"].apply(
    normalize_name
)

cureskin["normalized_name"] = cureskin["inci_name"].apply(
    normalize_name
)

incidb_names = set(ingredients["normalized_name"]) - {""}
cureskin_names = set(cureskin["normalized_name"]) - {""}

common_names = incidb_names & cureskin_names

print("Unique INCIDB names:", len(incidb_names))
print("Unique CureSkin names:", len(cureskin_names))
print("Exact normalized matches:", len(common_names))
print(
    "INCIDB names also found in CureSkin:",
    round(100 * len(common_names) / max(len(incidb_names), 1), 2),
    "%"
)

matched_names = pd.DataFrame({
    "normalized_name": sorted(common_names)
})

display(matched_names.head(20))

Unique INCIDB names: 1123
Unique CureSkin names: 1448
Exact normalized matches: 152
INCIDB names also found in CureSkin: 13.54 %

                normalized_name
0   adansonia digitata seed oil
1                       alcohol
2                     allantoin
3                 amyl cinnamal
4                          aqua
5    argania spinosa kernel oil
6                         aroma
7            ascorbyl palmitate
8       avena sativa kernel oil
9                benzyl alcohol
10              benzyl benzoate
11            benzyl salicylate
12  borago officinalis seed oil
13              butylene glycol
14  butylphenyl methylpropional
15  butyrospermum parkii butter
16     camelina sativa seed oil
17   camellia japonica seed oil
18   camellia oleifera seed oil
19   cananga odorata flower oil

In [13]:
flag_columns = [
    "is_active",
    "fa_trigger",
    "comedogenic",
    "fragrance",
    "eu_allergen",
    "pregnancy_caution"
]

for column in flag_columns:
    if column in cureskin.columns:
        print(f"\n{column}")
        print(cureskin[column].value_counts(dropna=False).head(10))

print("\nComedogenic ratings missing:",
      cureskin["comedogenic"].isna().sum())

print("Alcohol classifications missing:",
      cureskin["alcohol_type"].isna().sum())

is_active
is_active
0    1154
1     294
Name: count, dtype: int64

fa_trigger
fa_trigger
1.0    1199
NaN     205
0.0      44
Name: count, dtype: int64

comedogenic
comedogenic
NaN    1402
1.0      11
2.0      10
0.0       9
4.0       7
5.0       7
3.0       2
Name: count, dtype: int64

fragrance
fragrance
0    1355
1      93
Name: count, dtype: int64

eu_allergen
eu_allergen
0    1430
1      18
Name: count, dtype: int64

pregnancy_caution
pregnancy_caution
0    1349
1      99
Name: count, dtype: int64

Comedogenic ratings missing: 1402
Alcohol classifications missing: 1386

In [14]:
report = {
    "incidb_ingredients": len(ingredients),
    "incidb_products": len(products),
    "product_ingredient_rows": len(product_ingredients),
    "ingredient_name_map_rows": len(name_map),
    "cureskin_ingredients": len(cureskin),
    "exact_normalized_name_matches": len(common_names),
    "unresolved_name_mappings": len(unresolved),
    "product_ingredient_valid_ingredient_ids": int(
        product_ingredients["ingredient_id"].isin(ingredient_ids).sum()
    ),
    "product_ingredient_valid_product_ids": int(
        product_ingredients["product_id"].isin(product_ids).sum()
    )
}

report_path = DATA_DIR / "nb2_data_quality_report.json"
report_path.parent.mkdir(parents=True, exist_ok=True)

with open(report_path, "w", encoding="utf-8") as f:
    json.dump(report, f, indent=2)

print(json.dumps(report, indent=2))
print("Saved:", report_path)

{
  "incidb_ingredients": 1123,
  "incidb_products": 200,
  "product_ingredient_rows": 4089,
  "ingredient_name_map_rows": 1467,
  "cureskin_ingredients": 1448,
  "exact_normalized_name_matches": 152,
  "unresolved_name_mappings": 210,
  "product_ingredient_valid_ingredient_ids": 4089,
  "product_ingredient_valid_product_ids": 4089
}
Saved: /content/drive/MyDrive/ingredia_backup/ingredia_data/nb2_data_quality_report.json

In [16]:
import pandas as pd
import numpy as np
import re
import json
from pathlib import Path

DATA_DIR = Path("/content/drive/MyDrive/ingredia_backup/ingredia_data")
INCIDB_DIR = DATA_DIR / "incidb"

ingredients = pd.read_csv(INCIDB_DIR / "ingredients.csv", sep="|")
products = pd.read_csv(INCIDB_DIR / "products.csv", sep="|")
product_ingredients = pd.read_csv(
    INCIDB_DIR / "product_ingredients.csv", sep="|"
)
name_map = pd.read_csv(
    INCIDB_DIR / "ingredient_name_map.csv", sep="|"
)

cureskin = pd.read_csv(
    DATA_DIR / "cureskin_ingredient_flags.csv"
)

def normalize_name(value):
    if pd.isna(value):
        return ""
    value = str(value).casefold().strip()
    value = re.sub(r"\s+", " ", value)
    return value

ingredients["normalized_name"] = ingredients["inci_name"].apply(
    normalize_name
)

print("Empty ingredient names:",
      ingredients["normalized_name"].eq("").sum())

print("Duplicate normalized names:",
      ingredients["normalized_name"].duplicated().sum())

placeholder_pattern = (
    r"^\s*$|^\([^)]*\)$|^unknown$|^n/?a$|^null$"
)

ingredients["possible_placeholder"] = (
    ingredients["inci_name"]
    .fillna("")
    .astype(str)
    .str.match(placeholder_pattern, case=False)
)

print("\nPossible placeholder names:")
display(
    ingredients.loc[
        ingredients["possible_placeholder"],
        ["ingredient_id", "inci_name"]
    ].head(50)
)

Empty ingredient names: 0
Duplicate normalized names: 0

Possible placeholder names:

   ingredient_id            inci_name
0             51                ( /-)
1            203     (F.I.L B38252/3)
2            204     (F.I.L B48924/1)
3            347  (F.I.L,Y70037597/1)
4            407  (F.I.L.Z70042467/1)
5            420                (F01)
6            435       (FIL B44107/1)
7            550    (SD ALCOHOL 39-C)

In [17]:
product_counts = (
    product_ingredients
    .groupby("ingredient_id")["product_id"]
    .nunique()
    .rename("products_using_ingredient")
    .reset_index()
)

ingredient_coverage = ingredients.merge(
    product_counts,
    on="ingredient_id",
    how="left"
)

ingredient_coverage["products_using_ingredient"] = (
    ingredient_coverage["products_using_ingredient"]
    .fillna(0)
    .astype(int)
)

display(
    ingredient_coverage.sort_values(
        "products_using_ingredient",
        ascending=False
    )[
        ["ingredient_id", "inci_name", "functions",
         "products_using_ingredient"]
    ].head(25)
)

print(
    "Ingredients used in at least one sampled product:",
    (ingredient_coverage["products_using_ingredient"] > 0).sum()
)

print(
    "Ingredients not linked to sampled products:",
    (ingredient_coverage["products_using_ingredient"] == 0).sum()
)

,ingredient_id,inci_name,functions,products_using_ingredient
85,5225,AQUA,SOLVENT,154
723,31727,PARFUM,FRAGRANCE;PERFUMING,124
463,20582,GLYCERIN,DENATURANT;HAIR CONDITIONING;HUMECTANT;ORAL CA...,118
283,11910,CITRIC ACID,BUFFERING;CHELATING;FRAGRANCE,84
922,39072,SODIUM BENZOATE,ANTICORROSIVE;FRAGRANCE;PRESERVATIVE,76
620,26258,LINALOOL,DEODORANT;PERFUMING,75
618,26139,LIMONENE,DEODORANT;SOLVENT;PERFUMING,71
931,39264,SODIUM CHLORIDE,BULKING;FRAGRANCE;ORAL CARE;VISCOSITY CONTROLLING,71
765,33317,PHENOXYETHANOL,ANTIMICROBIAL;PRESERVATIVE,55
312,12864,COCAMIDOPROPYL BETAINE,ANTISTATIC;CLEANSING;SURFACTANT - FOAM BOOSTIN...,49
944,39599,SODIUM HYDROXIDE,BUFFERING;DENATURANT,48
948,39729,SODIUM LAURETH SULFATE,CLEANSING;SURFACTANT - EMULSIFYING;FOAMING;SUR...,47
1057,42628,TOCOPHEROL,ANTIOXIDANT;FRAGRANCE;SKIN CONDITIONING - MISC...,43
389,16230,DISODIUM EDTA,CHELATING;VISCOSITY CONTROLLING,42
118,6830,BENZYL ALCOHOL,PRESERVATIVE;SOLVENT;VISCOSITY CONTROLLING;PER...,39
1105,44889,XANTHAN GUM,BINDING;SURFACTANT - EMULSIFYING;EMULSION STAB...,36
505,22010,HEXYL CINNAMAL,PERFUMING,35
852,35607,PROPYLENE GLYCOL,HUMECTANT;FRAGRANCE;SOLVENT;VISCOSITY CONTROLL...,34
285,12074,CITRONELLOL,PERFUMING,34
220,10300,CETEARYL ALCOHOL,SKIN CONDITIONING - EMOLLIENT;SURFACTANT - EMU...,32
717,31500,PANTHENOL,ANTISTATIC;HAIR CONDITIONING;SKIN CONDITIONING,27
835,34902,POTASSIUM SORBATE,FRAGRANCE;PRESERVATIVE,24
471,20813,GLYCERYL STEARATE,SKIN CONDITIONING - EMOLLIENT;SURFACTANT - EMU...,23
93,5653,AROMA,FLAVOURING,23
1058,42695,TOCOPHERYL ACETATE,ANTIOXIDANT;SKIN CONDITIONING,22

Ingredients used in at least one sampled product: 1123
Ingredients not linked to sampled products: 0

In [18]:
name_map["normalized_raw_name"] = name_map["raw_name"].apply(
    normalize_name
)
name_map["normalized_canonical_name"] = (
    name_map["canonical_name"].apply(normalize_name)
)

mapping_audit = {
    "total_mappings": len(name_map),
    "empty_raw_names": int(
        name_map["normalized_raw_name"].eq("").sum()
    ),
    "empty_canonical_names": int(
        name_map["normalized_canonical_name"].eq("").sum()
    ),
    "duplicate_raw_names": int(
        name_map["normalized_raw_name"]
        .duplicated()
        .sum()
    ),
    "missing_ingredient_ids": int(
        name_map["ingredient_id"].isna().sum()
    )
}

print(json.dumps(mapping_audit, indent=2))

display(
    name_map[
        name_map["normalized_raw_name"].eq("")
        | name_map["normalized_canonical_name"].eq("")
    ].head(30)
)

{
  "total_mappings": 1467,
  "empty_raw_names": 0,
  "empty_canonical_names": 0,
  "duplicate_raw_names": 103,
  "missing_ingredient_ids": 0
}

Empty DataFrame
Columns: [raw_name, canonical_name, method, confidence, ingredient_id, part_index, split_rule, normalized_raw_name, normalized_canonical_name]
Index: []

In [19]:
name_map["normalized_raw_name"] = name_map["raw_name"].apply(
    normalize_name
)
name_map["normalized_canonical_name"] = (
    name_map["canonical_name"].apply(normalize_name)
)

mapping_audit = {
    "total_mappings": len(name_map),
    "empty_raw_names": int(
        name_map["normalized_raw_name"].eq("").sum()
    ),
    "empty_canonical_names": int(
        name_map["normalized_canonical_name"].eq("").sum()
    ),
    "duplicate_raw_names": int(
        name_map["normalized_raw_name"]
        .duplicated()
        .sum()
    ),
    "missing_ingredient_ids": int(
        name_map["ingredient_id"].isna().sum()
    )
}

print(json.dumps(mapping_audit, indent=2))

display(
    name_map[
        name_map["normalized_raw_name"].eq("")
        | name_map["normalized_canonical_name"].eq("")
    ].head(30)
)

{
  "total_mappings": 1467,
  "empty_raw_names": 0,
  "empty_canonical_names": 0,
  "duplicate_raw_names": 103,
  "missing_ingredient_ids": 0
}

Empty DataFrame
Columns: [raw_name, canonical_name, method, confidence, ingredient_id, part_index, split_rule, normalized_raw_name, normalized_canonical_name]
Index: []

In [20]:
fields_to_check = [
    "inci_name",
    "functions",
    "chemical_description",
    "cosing_restriction",
    "annex_ii",
    "annex_iii",
    "annex_iv",
    "annex_v",
    "annex_vi",
    "is_common_allergen",
    "allergen_source",
    "comedogenic_rating",
    "is_fungal_acne_trigger",
    "rating_source"
]

field_report = pd.DataFrame({
    "column": fields_to_check,
    "missing_count": [
        ingredients[col].isna().sum()
        if col in ingredients.columns else None
        for col in fields_to_check
    ],
    "missing_percent": [
        round(ingredients[col].isna().mean() * 100, 2)
        if col in ingredients.columns else None
        for col in fields_to_check
    ]
})

display(field_report)

                    column  missing_count  missing_percent
0                inci_name              0             0.00
1                functions            211            18.79
2     chemical_description            482            42.92
3       cosing_restriction            950            84.59
4                 annex_ii            200            17.81
5                annex_iii            200            17.81
6                 annex_iv            200            17.81
7                  annex_v            200            17.81
8                 annex_vi            200            17.81
9       is_common_allergen              0             0.00
10         allergen_source           1072            95.46
11      comedogenic_rating           1050            93.50
12  is_fungal_acne_trigger           1015            90.38
13           rating_source           1015            90.38

In [21]:
OUTPUT_DIR = DATA_DIR / "cleaning_audit"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

field_report.to_csv(
    OUTPUT_DIR / "ingredient_field_completeness.csv",
    index=False
)

ingredient_coverage.to_csv(
    OUTPUT_DIR / "ingredient_product_coverage.csv",
    index=False
)

name_map.to_csv(
    OUTPUT_DIR / "ingredient_name_mapping_audit.csv",
    index=False
)

with open(
    OUTPUT_DIR / "mapping_quality_summary.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(mapping_audit, f, indent=2)

print("Audit files saved to:", OUTPUT_DIR)

Audit files saved to: /content/drive/MyDrive/ingredia_backup/ingredia_data/cleaning_audit

In [22]:
# Find all rows whose normalized raw name occurs more than once.
duplicate_mask = name_map["normalized_raw_name"].duplicated(keep=False)

duplicate_mappings = (
    name_map.loc[duplicate_mask]
    .sort_values(["normalized_raw_name", "part_index"])
)

print("Rows involved in duplicate raw-name groups:",
      len(duplicate_mappings))

print("Number of distinct duplicated raw names:",
      duplicate_mappings["normalized_raw_name"].nunique())

display(
    duplicate_mappings[
        [
            "raw_name",
            "canonical_name",
            "method",
            "confidence",
            "ingredient_id",
            "part_index",
            "split_rule"
        ]
    ].head(100)
)

Rows involved in duplicate raw-name groups: 175
Number of distinct duplicated raw names: 72

,raw_name,canonical_name,method,confidence,ingredient_id,part_index,split_rule
760,/ INCI: ALOE BARBADENSIS (ALOE) LEAF JUICE*,INCI,unresolved_residual,0.00,23673,1,colon
62,/ INCI: ALOE BARBADENSIS (ALOE) LEAF JUICE*,ALOE BARBADENSIS LEAF JUICE,paren_stripped,0.80,4098,2,colon
11,1-NAPHTHOL. ACTIVATOR AQUA/WATER/EAU,1-NAPHTHOL,cleaned,0.85,842,1,period
42,1-NAPHTHOL. ACTIVATOR AQUA/WATER/EAU,ACTIVATOR AQUA/WATER/EAU,unresolved_residual,0.00,3315,2,period
21,695126 41 INGREDIENTS : AQUA / WATER,695126 41 INGREDIENTS,unresolved_residual,0.00,2291,1,colon
...,...,...,...,...,...,...,...
1325,ISOPROPYL PALMITATE STEARIC ACID,STEARIC ACID,split,0.80,40970,2,NaN
827,LIMONENE. LINALOOL,LIMONENE,cleaned,0.85,26139,1,period
830,LIMONENE. LINALOOL,LINALOOL,cleaned,0.85,26258,2,period
841,LZM ENTHALT: NATR UMFLUORID (1450 PPM F) INGRE...,"LZM ENTHALT, NATR UMFLUORID (1450 PPM F) INGRE...",unresolved_residual,0.00,26740,1,colon
133,LZM ENTHALT: NATR UMFLUORID (1450 PPM F) INGRE...,AQUA,cleaned,0.85,5225,2,colon

In [23]:
duplicate_summary = (
    duplicate_mappings
    .groupby("normalized_raw_name")
    .agg(
        row_count=("normalized_raw_name", "size"),
        canonical_names=("canonical_name", "nunique"),
        ingredient_ids=("ingredient_id", "nunique"),
        methods=("method", "nunique")
    )
    .reset_index()
)

print("Repeated names pointing to multiple ingredient IDs:")
display(
    duplicate_summary[
        duplicate_summary["ingredient_ids"] > 1
    ].head(50)
)

print("Repeated names with multiple canonical names:")
display(
    duplicate_summary[
        duplicate_summary["canonical_names"] > 1
    ].head(50)
)

Repeated names pointing to multiple ingredient IDs:

,normalized_raw_name,row_count,canonical_names,ingredient_ids,methods
0,/ inci: aloe barbadensis (aloe) leaf juice*,2,2,2,2
1,1-naphthol. activator aqua/water/eau,2,2,2,2
2,695126 41 ingredients : aqua / water,2,2,2,2
3,737201 6 - ingredients : aqua / water,2,2,2,2
4,8855963-ingredients: aqua/water,2,2,2,2
5,[may contain/peut contenir/+/-:ferric ammonium...,5,5,5,2
6,"[may contain/peut contenir/+/-:mica, titanium ...",10,10,10,3
7,alcohol denat. (sd alcohol 39-c),2,2,2,2
8,alpha-terpinene anethole,2,2,2,1
9,ammonium sulfate. emulsion révélatrice : aqua,3,3,3,2
10,aqua | aloe barbadensis leaf juice | glycerin ...,8,8,8,1
11,aroma limonene,2,2,2,1
12,behenyl trimonium chloride cannabis sativa (he...,2,2,2,2
13,c12-15 alkyl benzoate glycerin butyl methoxydi...,3,3,3,1
14,carbomer fragrance(parfum),2,2,2,2
15,cellulose gum benzyl alcohol,2,2,2,1
16,ceramide eop ceramide eos,2,2,2,1
17,ci 77891. contains sodium fluoride (1450 ppm f),2,2,2,2
18,citronellol***. *ingredients from organic farm...,2,2,2,2
19,coco-betaine pentylene glycol,2,2,2,1
20,copper gluconate. fabricado y exportado por: j...,2,2,2,2
21,coumarin limonene,2,2,2,1
22,crème colorante : aqua,2,2,2,2
23,dimethicone. azelaic acid,2,2,2,1
24,disodium edta. [bi 446],2,2,2,2
25,duschgel mit verwöhnendem duft nach magnolie. ...,2,2,2,2
26,ethylhexyl salicylate vp/hexadecene copolymer,2,2,2,1
27,etidronic acid. bonding treatment aqua/water/eau,2,2,2,2
28,eucalyptus globulus leaf oil*. *ingrédients is...,2,2,2,2
29,fructose. non parfumée,2,2,2,2
30,geraniol. www,2,2,2,2
31,glycerin panthenol,2,2,2,1
32,glyceryl stearate se algin,2,2,2,1
33,hexamethylindanopyran. testowa,2,2,2,2
34,hexyl cinnamal linalool,2,2,2,1
35,hexyl cinnamal. masque soin : aqua,3,3,3,2
36,inactive ingredients glycerin,2,2,2,2
37,isopropyl palmitate stearic acid,2,2,2,1
38,limonene. linalool,2,2,2,1
39,lzm enthalt: natr umfluorid (1450 ppm f) ingre...,2,2,2,2
40,microcrystalline cellulose sodium hydroxide,2,2,2,1
41,naturkosmetik ohne kompromisse - mit hochwerti...,2,2,2,2
42,panthenol allantoin,2,2,2,1
43,panthenol. glycol distearate,2,2,2,1
44,parfum / fragrance. (f.i.l b38252/3),2,2,2,2
45,parfum / fragrance. (f.i.l b48924/1),2,2,2,2
46,parfum / fragrance. (fil b44107/1),2,2,2,2
47,parfum ethylhexyl methoxycinnamate,2,2,2,1
48,parfum/fragrance. (f.i.l. y70037597/1),2,2,2,2
49,parfum/fragrance. (f.i.l.z70042467/1),2,2,2,2

Repeated names with multiple canonical names:

,normalized_raw_name,row_count,canonical_names,ingredient_ids,methods
0,/ inci: aloe barbadensis (aloe) leaf juice*,2,2,2,2
1,1-naphthol. activator aqua/water/eau,2,2,2,2
2,695126 41 ingredients : aqua / water,2,2,2,2
3,737201 6 - ingredients : aqua / water,2,2,2,2
4,8855963-ingredients: aqua/water,2,2,2,2
5,[may contain/peut contenir/+/-:ferric ammonium...,5,5,5,2
6,"[may contain/peut contenir/+/-:mica, titanium ...",10,10,10,3
7,alcohol denat. (sd alcohol 39-c),2,2,2,2
8,alpha-terpinene anethole,2,2,2,1
9,ammonium sulfate. emulsion révélatrice : aqua,3,3,3,2
10,aqua | aloe barbadensis leaf juice | glycerin ...,8,8,8,1
11,aroma limonene,2,2,2,1
12,behenyl trimonium chloride cannabis sativa (he...,2,2,2,2
13,c12-15 alkyl benzoate glycerin butyl methoxydi...,3,3,3,1
14,carbomer fragrance(parfum),2,2,2,2
15,cellulose gum benzyl alcohol,2,2,2,1
16,ceramide eop ceramide eos,2,2,2,1
17,ci 77891. contains sodium fluoride (1450 ppm f),2,2,2,2
18,citronellol***. *ingredients from organic farm...,2,2,2,2
19,coco-betaine pentylene glycol,2,2,2,1
20,copper gluconate. fabricado y exportado por: j...,2,2,2,2
21,coumarin limonene,2,2,2,1
22,crème colorante : aqua,2,2,2,2
23,dimethicone. azelaic acid,2,2,2,1
24,disodium edta. [bi 446],2,2,2,2
25,duschgel mit verwöhnendem duft nach magnolie. ...,2,2,2,2
26,ethylhexyl salicylate vp/hexadecene copolymer,2,2,2,1
27,etidronic acid. bonding treatment aqua/water/eau,2,2,2,2
28,eucalyptus globulus leaf oil*. *ingrédients is...,2,2,2,2
29,fructose. non parfumée,2,2,2,2
30,geraniol. www,2,2,2,2
31,glycerin panthenol,2,2,2,1
32,glyceryl stearate se algin,2,2,2,1
33,hexamethylindanopyran. testowa,2,2,2,2
34,hexyl cinnamal linalool,2,2,2,1
35,hexyl cinnamal. masque soin : aqua,3,3,3,2
36,inactive ingredients glycerin,2,2,2,2
37,isopropyl palmitate stearic acid,2,2,2,1
38,limonene. linalool,2,2,2,1
39,lzm enthalt: natr umfluorid (1450 ppm f) ingre...,2,2,2,2
40,microcrystalline cellulose sodium hydroxide,2,2,2,1
41,naturkosmetik ohne kompromisse - mit hochwerti...,2,2,2,2
42,panthenol allantoin,2,2,2,1
43,panthenol. glycol distearate,2,2,2,1
44,parfum / fragrance. (f.i.l b38252/3),2,2,2,2
45,parfum / fragrance. (f.i.l b48924/1),2,2,2,2
46,parfum / fragrance. (fil b44107/1),2,2,2,2
47,parfum ethylhexyl methoxycinnamate,2,2,2,1
48,parfum/fragrance. (f.i.l. y70037597/1),2,2,2,2
49,parfum/fragrance. (f.i.l.z70042467/1),2,2,2,2

In [24]:
from pathlib import Path
import pandas as pd
import re
import json

# Persistent output directory on Google Drive
OUTPUT_DIR = Path(
    "/content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned"
)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

clean_master = ingredients.copy()

# Standardized search key; preserve the original INCI name.
clean_master["normalized_name"] = (
    clean_master["inci_name"]
    .fillna("")
    .astype(str)
    .str.casefold()
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

# Flag suspicious names for manual review, not automatic deletion.
placeholder_pattern = (
    r"^\s*$|^\([^)]*\)$|^unknown$|^n/?a$|^null$"
)

clean_master["needs_name_review"] = (
    clean_master["inci_name"]
    .fillna("")
    .astype(str)
    .str.match(placeholder_pattern, case=False)
)

# Missing values remain missing.
clean_master["functions_missing"] = (
    clean_master["functions"].isna()
    if "functions" in clean_master.columns
    else True
)

clean_master["description_missing"] = (
    clean_master["chemical_description"].isna()
    if "chemical_description" in clean_master.columns
    else True
)

clean_master["comedogenic_rating_missing"] = (
    clean_master["comedogenic_rating"].isna()
    if "comedogenic_rating" in clean_master.columns
    else True
)

clean_master["fungal_acne_flag_missing"] = (
    clean_master["is_fungal_acne_trigger"].isna()
    if "is_fungal_acne_trigger" in clean_master.columns
    else True
)

# Attach the number of products linked to each ingredient.
clean_master = clean_master.merge(
    product_counts,
    on="ingredient_id",
    how="left",
    validate="one_to_one"
)

clean_master["products_using_ingredient"] = (
    clean_master["products_using_ingredient"].fillna(0).astype(int)
)

# Export the review-ready working copy.
clean_master.to_csv(
    OUTPUT_DIR / "ingredient_master_working.csv",
    index=False
)

review_rows = clean_master[
    clean_master["needs_name_review"]
]

review_rows.to_csv(
    OUTPUT_DIR / "ingredient_names_for_review.csv",
    index=False
)

print("Working ingredient master:", len(clean_master))
print("Names requiring review:", len(review_rows))
print("Saved to:", OUTPUT_DIR)

Working ingredient master: 1123
Names requiring review: 8
Saved to: /content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned

In [25]:
# Summarize how the name-mapping pipeline created its mappings.

print("Mapping methods:")
display(
    name_map["method"]
    .fillna("MISSING")
    .value_counts()
    .rename_axis("method")
    .reset_index(name="count")
)

print("\nConfidence distribution:")
display(
    pd.to_numeric(name_map["confidence"], errors="coerce")
    .describe()
    .to_frame("confidence")
)

print("\nLow-confidence mappings (if confidence is numeric):")
name_map["confidence_num"] = pd.to_numeric(
    name_map["confidence"], errors="coerce"
)

display(
    name_map[
        name_map["confidence_num"].lt(0.8)
        | name_map["confidence_num"].isna()
    ][
        [
            "raw_name", "canonical_name", "method",
            "confidence", "ingredient_id", "part_index"
        ]
    ].head(50)
)

Mapping methods:

                method  count
0                exact    916
1           unresolved    164
2       paren_stripped    116
3              cleaned    108
4                split     68
5  unresolved_residual     46
6        slash_variant     30
7          synonym_map     10
8       slash_same_cas      8
9             typo_map      1

Confidence distribution:

        confidence
count  1467.000000
mean      0.822836
std       0.342917
min       0.000000
25%       0.850000
50%       1.000000
75%       1.000000
max       1.000000

Low-confidence mappings (if confidence is numeric):

,raw_name,canonical_name,method,confidence,ingredient_id,part_index
0,TOCOPHEROL. MAY CONTAIN (+/-): CI 77891,( /-),unresolved_residual,0.00,51,2
1,PARFUM / FRAGRANCE. (F.I.L B38252/3),(F.I.L B38252/3),unresolved_residual,0.00,203,2
2,PARFUM / FRAGRANCE. (F.I.L B48924/1),(F.I.L B48924/1),unresolved_residual,0.00,204,2
3,PARFUM/FRAGRANCE. (F.I.L. Y70037597/1),"(F.I.L,Y70037597/1)",unresolved_residual,0.00,347,2
4,PARFUM/FRAGRANCE. (F.I.L.Z70042467/1),(F.I.L.Z70042467/1),unresolved_residual,0.00,407,2
5,(F01),(F01),unresolved,0.00,420,1
6,PARFUM / FRAGRANCE. (FIL B44107/1),(FIL B44107/1),unresolved_residual,0.00,435,2
7,ALCOHOL DENAT. (SD ALCOHOL 39-C),(SD ALCOHOL 39-C),unresolved_residual,0.00,550,2
12,12M BEIERSDOCF OUY HI,12M BEIERSDOCF OUY HI,unresolved,0.00,1286,1
21,695126 41 INGREDIENTS : AQUA / WATER,695126 41 INGREDIENTS,unresolved_residual,0.00,2291,1
22,737201 6 - INGREDIENTS : AQUA / WATER,737201 6 - INGREDIENTS,unresolved_residual,0.00,2342,1
23,8855963-INGREDIENTS: AQUA/WATER,8855963-INGREDIENTS,unresolved_residual,0.00,2493,1
25,ACETYL ALCOHOL,ACETYL ALCOHOL,unresolved,0.00,2886,1
32,ACRYLATE/C10-30 ALKYL ACRYLATE CROSSPOLYMER,ACRYLATE/C10-30 ALKYL ACRYLATE CROSSPOLYMER,unresolved,0.00,3136,1
42,1-NAPHTHOL. ACTIVATOR AQUA/WATER/EAU,ACTIVATOR AQUA/WATER/EAU,unresolved_residual,0.00,3315,2
52,ALCOHOL DENAT. (SD ALCOHOL 39-C),ALCOHOL DENAT.,synonym_map,0.75,3781,1
59,ALLANTON COCAMIDOPROPYL BETAINE,ALLANTON COCAMIDOPROPYL BETAINE,unresolved,0.00,3975,1
71,ALPHA-ISOMETHYL LONONE,ALPHA-ISOMETHYL LONONE,unresolved,0.00,4303,1
75,ALUMINIUM CHLOROHYDRATE,ALUMINIUM CHLOROHYDRATE,unresolved,0.00,4407,1
76,ALUMINIUM ZIRCONIUM TETRACHLOROHYDREX GLY,ALUMINIUM ZIRCONIUM TETRACHLOROHYDREX GLY,unresolved,0.00,4422,1
84,AMARA (BITTER ORANGE) FLOWER OIL,AMARA (BITTER ORANGE) FLOWER OIL,unresolved,0.00,4508,1
96,AMYL CINNAMYL ALCOHOL,AMYL CINNAMYL ALCOHOL,unresolved,0.00,4766,1
104,APHANIZOMENON FLOS-AQUAE EXTRACT,APHANIZOMENON FLOS-AQUAE EXTRACT,unresolved,0.00,5123,1
105,APHANIZOMENON FLOS-AQUAE EXTRACT*,APHANIZOMENON FLOS-AQUAE EXTRACT,unresolved,0.00,5123,1
107,695126 41 INGREDIENTS : AQUA / WATER,AQUA,slash_variant,0.70,5225,2
108,737201 6 - INGREDIENTS : AQUA / WATER,AQUA,slash_variant,0.70,5225,2
109,8855963-INGREDIENTS: AQUA/WATER,AQUA,slash_variant,0.70,5225,2
126,EAU),AQUA,synonym_map,0.75,5225,1
143,AQUA VATER),AQUA VATER),unresolved,0.00,5328,1
178,BEHENYL TRIMONIUM CHLORIDE CANNABIS SATIVA (HE...,BEHENYL TRIMONIUM CHLORIDE,unresolved_residual,0.00,6618,1
188,BENZTL SALICYLATE,BENZTL SALICYLATE,unresolved,0.00,6783,1
193,BENZYL SALL CYLATE**,BENZYL SALL CYLATE,unresolved,0.00,6952,1
194,BENZYLALCOHOL,BENZYLALCOHOL,unresolved,0.00,6971,1
200,DISODIUM EDTA. [BI 446],BI 446,unresolved_residual,0.00,7157,2
206,BIS-ASMINOPROPYL DIMETHICONE,BIS-ASMINOPROPYL DIMETHICONE,unresolved,0.00,7291,1
213,BLUE 1 LAKE (CI 42090),BLUE 1 LAKE (CI 42090),unresolved,0.00,7509,1
214,BLUE 1 LAKE (CI 42090) *,BLUE 1 LAKE (CI 42090),unresolved,0.00,7509,1
215,BONDING PRIMER AQUA/WATER/EAU,BONDING PRIMER AQUA/WATER/EAU,unresolved,0.00,7574,1
216,ETIDRONIC ACID. BONDING TREATMENT AQUA/WATER/EAU,BONDING TREATMENT AQUA/WATER/EAU,unresolved_residual,0.00,7575,2
220,BUTYENE GLYCOL,BUTYENE GLYCOL,unresolved,0.00,7910,1
221,BUTYL ACÉTATE,BUTYL AC TATE,unresolved,0.00,7919,1
230,BUTYROSPERMUM PARKII (SHEA BUTTER),BUTYROSPERMUM PARKII (SHEA BUTTER),unresolved,0.00,8221,1
238,BUTYROSPERMUMPARKII BUTTER,BUTYROSPERMUMPARKII BUTTER,unresolved,0.00,8292,1
239,C.I.16255,C.I.16255,unresolved,0.00,8486,1
241,C12-15 ALKYL BENZOALE CETEARYL ALCOHOL,C12-15 ALKYL BENZOALE CETEARYL ALCOHOL,unresolved,0.00,8620,1
265,CAMPHOC FAMESOL,CAMPHOC FAMESOL,unresolved,0.00,9174,1
268,CANANGA ODORATA OIL / CANANGA ODORATA FLOWER OIL,CANANGA ODORATA OIL / CANANGA ODORATA FLOWER OIL,unresolved,0.00,9206,1
270,CANDELILLA CERA/ CANDELILLA WAX,CANDELILLA CERA/ CANDELILLA WAX,unresolved,0.00,9227,1
302,CERA ALBA / BEESWAX,CERA ALBA,slash_same_cas,0.75,10046,1
303,CERA ALBA/BEESWAX,CERA ALBA,slash_same_cas,0.75,10046,1

In [26]:
import re
import pandas as pd

mapping_review = name_map.copy()

mapping_review["raw_name_clean"] = (
    mapping_review["raw_name"]
    .fillna("")
    .astype(str)
    .str.strip()
)

patterns = {
    "manufacturer_code": r"\bF\.?I\.?L\.?\b|F\d{2}|B\d{4,}",
    "may_contain_statement": r"may contain|peut contenir|may contain/peut",
    "label_metadata": (
        r"ingredients?\s*:|inactive ingredients|"
        r"activator|emulsion|bonding treatment"
    ),
    "possible_multiple_ingredients": r"\s[|]\s|;",
    "possible_product_text": (
        r"www\.|fabricado|exportado|duschgel|"
        r"cr[eè]me colorante|naturkosmetik"
    )
}

for flag, pattern in patterns.items():
    mapping_review[flag] = mapping_review["raw_name_clean"].str.contains(
        pattern, case=False, regex=True, na=False
    )

flag_columns = list(patterns.keys())

mapping_review["needs_manual_review"] = mapping_review[
    flag_columns
].any(axis=1)

print("Mappings requiring review:",
      int(mapping_review["needs_manual_review"].sum()))

display(
    mapping_review.loc[
        mapping_review["needs_manual_review"],
        [
            "raw_name", "canonical_name", "method",
            "confidence", "ingredient_id"
        ] + flag_columns
    ].head(60)
)

mapping_review.to_csv(
    OUTPUT_DIR / "ingredient_mapping_review.csv",
    index=False
)

Mappings requiring review: 78

,raw_name,canonical_name,method,confidence,ingredient_id,manufacturer_code,may_contain_statement,label_metadata,possible_multiple_ingredients,possible_product_text
0,TOCOPHEROL. MAY CONTAIN (+/-): CI 77891,( /-),unresolved_residual,0.00,51,False,True,False,False,False
1,PARFUM / FRAGRANCE. (F.I.L B38252/3),(F.I.L B38252/3),unresolved_residual,0.00,203,True,False,False,False,False
2,PARFUM / FRAGRANCE. (F.I.L B48924/1),(F.I.L B48924/1),unresolved_residual,0.00,204,True,False,False,False,False
3,PARFUM/FRAGRANCE. (F.I.L. Y70037597/1),"(F.I.L,Y70037597/1)",unresolved_residual,0.00,347,True,False,False,False,False
4,PARFUM/FRAGRANCE. (F.I.L.Z70042467/1),(F.I.L.Z70042467/1),unresolved_residual,0.00,407,True,False,False,False,False
5,(F01),(F01),unresolved,0.00,420,True,False,False,False,False
6,PARFUM / FRAGRANCE. (FIL B44107/1),(FIL B44107/1),unresolved_residual,0.00,435,True,False,False,False,False
11,1-NAPHTHOL. ACTIVATOR AQUA/WATER/EAU,1-NAPHTHOL,cleaned,0.85,842,False,False,True,False,False
21,695126 41 INGREDIENTS : AQUA / WATER,695126 41 INGREDIENTS,unresolved_residual,0.00,2291,False,False,True,False,False
22,737201 6 - INGREDIENTS : AQUA / WATER,737201 6 - INGREDIENTS,unresolved_residual,0.00,2342,False,False,True,False,False
23,8855963-INGREDIENTS: AQUA/WATER,8855963-INGREDIENTS,unresolved_residual,0.00,2493,False,False,True,False,False
42,1-NAPHTHOL. ACTIVATOR AQUA/WATER/EAU,ACTIVATOR AQUA/WATER/EAU,unresolved_residual,0.00,3315,False,False,True,False,False
67,AQUA | ALOE BARBADENSIS LEAF JUICE | GLYCERIN ...,ALOE BARBADENSIS LEAF JUICE,split,0.80,4098,False,False,False,True,False
79,[MAY CONTAIN/PEUT CONTENIR/+/-:FERRIC AMMONIUM...,ALUMINUM POWDER,paren_stripped,0.80,4459,False,True,False,False,False
80,"[MAY CONTAIN/PEUT CONTENIR/+/-:MICA, TITANIUM ...",ALUMINUM POWDER,paren_stripped,0.80,4459,False,True,False,False,False
93,AMMONIUM SULFATE. EMULSION RÉVÉLATRICE : AQUA,AMMONIUM SULFATE,cleaned,0.85,4691,False,False,True,False,False
106,. INGREDIENTS: AQUA,AQUA,cleaned,0.85,5225,False,False,True,False,False
107,695126 41 INGREDIENTS : AQUA / WATER,AQUA,slash_variant,0.70,5225,False,False,True,False,False
108,737201 6 - INGREDIENTS : AQUA / WATER,AQUA,slash_variant,0.70,5225,False,False,True,False,False
109,8855963-INGREDIENTS: AQUA/WATER,AQUA,slash_variant,0.70,5225,False,False,True,False,False
110,AMMONIUM SULFATE. EMULSION RÉVÉLATRICE : AQUA,AQUA,cleaned,0.85,5225,False,False,True,False,False
118,AQUA | ALOE BARBADENSIS LEAF JUICE | GLYCERIN ...,AQUA,split,0.80,5225,False,False,False,True,False
123,CRÈME COLORANTE : AQUA,AQUA,cleaned,0.85,5225,False,False,False,False,True
124,DUSCHGEL MIT VERWÖHNENDEM DUFT NACH MAGNOLIE. ...,AQUA,cleaned,0.85,5225,False,False,True,False,True
133,LZM ENTHALT: NATR UMFLUORID (1450 PPM F) INGRE...,AQUA,cleaned,0.85,5225,False,False,True,False,False
134,NATURKOSMETIK OHNE KOMPROMISSE - MIT HOCHWERTI...,AQUA,cleaned,0.85,5225,False,False,True,False,True
216,ETIDRONIC ACID. BONDING TREATMENT AQUA/WATER/EAU,BONDING TREATMENT AQUA/WATER/EAU,unresolved_residual,0.00,7575,False,False,True,False,False
379,"TIN OXIDE. [+/- MAY CONTAIN: CI 77491, CI 7749...",CI 75470 / CARMINE,unresolved_residual,0.00,11332,False,True,False,False,False
384,"TIN OXIDE. [+/- MAY CONTAIN: CI 77491, CI 7749...",CI 77007,slash_same_cas,0.65,11353,False,True,False,False,False
388,MAY CONTAIN: CI 77491,CI 77491,exact,0.90,11405,False,True,False,False,False
389,"TIN OXIDE. [+/- MAY CONTAIN: CI 77491, CI 7749...",CI 77491,exact,0.90,11405,False,True,False,False,False
391,"TIN OXIDE. [+/- MAY CONTAIN: CI 77491, CI 7749...",CI 77492,exact,0.90,11440,False,True,False,False,False
394,"TIN OXIDE. [+/- MAY CONTAIN: CI 77491, CI 7749...",CI 77499 / IRON OXIDES,unresolved_residual,0.00,11458,False,True,False,False,False
399,"TIN OXIDE. [+/- MAY CONTAIN: CI 77491, CI 7749...",CI 77891,slash_same_cas,0.65,11548,False,True,False,False,False
401,TOCOPHEROL. MAY CONTAIN (+/-): CI 77891,CI 77891,exact,0.90,11548,False,True,False,False,False
475,CODE F.I.L. : C182660/1,CODE F.I.L. C182660/1,unresolved,0.00,13315,True,False,False,False,False
482,COPPER GLUCONATE. FABRICADO Y EXPORTADO POR: J...,COPPER GLUCONATE,cleaned,0.85,14134,False,False,False,False,True
486,CRÈME COLORANTE : AQUA,CR ME COLORANTE,unresolved_residual,0.00,14318,False,False,False,False,True
499,"[MAY CONTAIN/PEUT CONTENIR/+/-:MICA, TITANIUM ...","D C BLACK NO. 2 (CI 77266), CLEARLY QUICK TOP ...",unresolved_residual,0.00,14723,False,True,False,False,False
500,"[MAY CONTAIN/PEUT CONTENIR/+/-:MICA, TITANIUM ...",D C RED NO. 34 CALCIUM LAKE (CI 15880),unresolved_residual,0.00,14748,False,True,False,False,False
502,[MAY CONTAIN/PEUT CONTENIR/+/-:FERRIC AMMONIUM...,D C RED NO. 7 CALCIUM LAKE (CI 15850),unresolved_residual,0.00,14754,False,True,False,False,False
504,AQUA | ALOE BARBADENSIS LEAF JUICE | GLYCERIN ...,DECYL GLUCOSIDE,split,0.80,15170,False,False,False,True,False
558,DUSCHGEL MIT VERWÖHNENDEM DUFT NACH MAGNOLIE. ...,DUSCHGEL MIT VERW HNENDEM DUFT NACH MAGNOLIE,unresolved_residual,0.00,16741,False,False,True,False,True
562,AMMONIUM SULFATE. EMULSION RÉVÉLATRICE : AQUA,EMULSION R V LATRICE,unresolved_residual,0.00,17266,False,False,True,False,False
588,ETIDRONIC ACID. BONDING TREATMENT AQUA/WATER/EAU,ETIDRONIC ACID,cleaned,0.85,18166,False,False,True,False,False
599,COPPER GLUCONATE. FABRICADO Y EXPORTADO POR: J...,"FABRICADO Y EXPORTADO POR, JOHNSON HYDROXIDE",unresolved_residual,0.00,18753,False,False,False,False,True
603,"[MAY CONTAIN/PEUT CONTENIR/+/-:MICA, TITANIUM ...",FD C YELLOW NO. 5 ALUMINUM LAKE (CI 19140),unresolved_residual,0.00,18925,False,True,False,False,False
604,[MAY CONTAIN/PEUT CONTENIR/+/-:FERRIC AMMONIUM...,"FD C YELLOW NO. 5 ALUMINUM LAKE (CI 19140), D ...",unresolved_residual,0.00,18926,False,True,False,False,False
606,[MAY CONTAIN/PEUT CONTENIR/+/-:FERRIC AMMONIUM...,FERRIC AMMONIUM FERROCYANIDE,paren_stripped,0.80,18978,False,True,False,False,False
607,"[MAY CONTAIN/PEUT CONTENIR/+/-:MICA, TITANIUM ...",FERRIC AMMONIUM FERROCYANIDE,paren_stripped,0.80,18978,False,True,False,False,False
620,FUSANUS SPICATUS (SANDALWOOD) WOOD OIL &QUOT;C...,FUSANUS SPICATUS (SANDALWOOD) WOOD OIL CERTIFI...,unresolved,0.00,19741,False,False,False,True,False
637,AQUA | ALOE BARBADENSIS LEAF JUICE | GLYCERIN ...,GLYCERIN,split,0.80,20582,False,False,False,True,False
644,INACTIVE INGREDIENTS GLYCERIN,GLYCERIN,cleaned,0.85,20582,False,False,True,False,False
759,INACTIVE INGREDIENTS GLYCERIN,INACTIVE INGREDIENTS,unresolved_residual,0.00,23627,False,False,True,False,False
792,AQUA | ALOE BARBADENSIS LEAF JUICE | GLYCERIN ...,LACTIC ACID,split,0.80,25176,False,False,False,True,False
819,AQUA | ALOE BARBADENSIS LEAF JUICE | GLYCERIN ...,LEVULINIC ACID,split,0.80,25995,False,False,False,True,False
841,LZM ENTHALT: NATR UMFLUORID (1450 PPM F) INGRE...,"LZM ENTHALT, NATR UMFLUORID (1450 PPM F) INGRE...",unresolved_residual,0.00,26740,False,False,True,False,False
859,"[MAY CONTAIN/PEUT CONTENIR/+/-:MICA, TITANIUM ...","MANGANESE VIOLET (CI 77742), D C RED NO. 6 BAR...",unresolved_residual,0.00,27218,False,True,False,False,False
865,"TIN OXIDE. [+/- MAY CONTAIN: CI 77491, CI 7749...",MAY CONTAIN,unresolved_residual,0.00,27494,False,True,False,False,False
887,"TIN OXIDE. [+/- MAY CONTAIN: CI 77491, CI 7749...",MICA,exact,0.90,28295,False,True,False,False,False

In [27]:
import pandas as pd
from pathlib import Path

# Reuse mapping_review from Cell 10.
# This creates a review file; it does not alter your source data.

review_queue = mapping_review[
    mapping_review["needs_manual_review"]
].copy()

def recommend_review(row):
    method = str(row.get("method", "")).lower()
    confidence = pd.to_numeric(
        pd.Series([row.get("confidence")]), errors="coerce"
    ).iloc[0]

    if row.get("manufacturer_code", False):
        return "Separate manufacturer code from ingredient identity"

    if row.get("may_contain_statement", False):
        return "Review optional colorants and may-contain context"

    if row.get("possible_product_text", False):
        return "Separate product description from ingredient text"

    if row.get("possible_multiple_ingredients", False):
        return "Verify ingredient splitting and each resulting mapping"

    if method in {"unresolved", "unresolved_residual"}:
        return "Manual identification required; do not auto-map"

    if pd.isna(confidence) or confidence < 0.8:
        return "Verify canonical ingredient against a trusted source"

    return "Review context before accepting mapping"

review_queue["recommended_action"] = review_queue.apply(
    recommend_review, axis=1
)

review_queue["review_status"] = "pending"

# Put low-confidence and unresolved mappings first.
review_queue["confidence_num"] = pd.to_numeric(
    review_queue["confidence"], errors="coerce"
)

review_queue = review_queue.sort_values(
    ["confidence_num", "method"],
    ascending=[True, True],
    na_position="first"
)

review_columns = [
    "raw_name",
    "canonical_name",
    "method",
    "confidence",
    "ingredient_id",
    "part_index",
    "recommended_action",
    "review_status",
]

review_columns = [
    col for col in review_columns if col in review_queue.columns
]

review_path = OUTPUT_DIR / "ingredient_mapping_review_queue.csv"

review_queue[review_columns].to_csv(
    review_path, index=False
)

print("Review queue rows:", len(review_queue))
print("Saved to:", review_path)
display(review_queue[review_columns].head(20))

Review queue rows: 78
Saved to: /content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned/ingredient_mapping_review_queue.csv

,raw_name,canonical_name,method,confidence,ingredient_id,part_index,recommended_action,review_status
5,(F01),(F01),unresolved,0.0,420,1,Separate manufacturer code from ingredient ide...,pending
475,CODE F.I.L. : C182660/1,CODE F.I.L. C182660/1,unresolved,0.0,13315,1,Separate manufacturer code from ingredient ide...,pending
620,FUSANUS SPICATUS (SANDALWOOD) WOOD OIL &QUOT;C...,FUSANUS SPICATUS (SANDALWOOD) WOOD OIL CERTIFI...,unresolved,0.0,19741,1,Verify ingredient splitting and each resulting...,pending
0,TOCOPHEROL. MAY CONTAIN (+/-): CI 77891,( /-),unresolved_residual,0.0,51,2,Review optional colorants and may-contain context,pending
1,PARFUM / FRAGRANCE. (F.I.L B38252/3),(F.I.L B38252/3),unresolved_residual,0.0,203,2,Separate manufacturer code from ingredient ide...,pending
2,PARFUM / FRAGRANCE. (F.I.L B48924/1),(F.I.L B48924/1),unresolved_residual,0.0,204,2,Separate manufacturer code from ingredient ide...,pending
3,PARFUM/FRAGRANCE. (F.I.L. Y70037597/1),"(F.I.L,Y70037597/1)",unresolved_residual,0.0,347,2,Separate manufacturer code from ingredient ide...,pending
4,PARFUM/FRAGRANCE. (F.I.L.Z70042467/1),(F.I.L.Z70042467/1),unresolved_residual,0.0,407,2,Separate manufacturer code from ingredient ide...,pending
6,PARFUM / FRAGRANCE. (FIL B44107/1),(FIL B44107/1),unresolved_residual,0.0,435,2,Separate manufacturer code from ingredient ide...,pending
21,695126 41 INGREDIENTS : AQUA / WATER,695126 41 INGREDIENTS,unresolved_residual,0.0,2291,1,Manual identification required; do not auto-map,pending
22,737201 6 - INGREDIENTS : AQUA / WATER,737201 6 - INGREDIENTS,unresolved_residual,0.0,2342,1,Manual identification required; do not auto-map,pending
23,8855963-INGREDIENTS: AQUA/WATER,8855963-INGREDIENTS,unresolved_residual,0.0,2493,1,Manual identification required; do not auto-map,pending
42,1-NAPHTHOL. ACTIVATOR AQUA/WATER/EAU,ACTIVATOR AQUA/WATER/EAU,unresolved_residual,0.0,3315,2,Manual identification required; do not auto-map,pending
216,ETIDRONIC ACID. BONDING TREATMENT AQUA/WATER/EAU,BONDING TREATMENT AQUA/WATER/EAU,unresolved_residual,0.0,7575,2,Manual identification required; do not auto-map,pending
379,"TIN OXIDE. [+/- MAY CONTAIN: CI 77491, CI 7749...",CI 75470 / CARMINE,unresolved_residual,0.0,11332,8,Review optional colorants and may-contain context,pending
394,"TIN OXIDE. [+/- MAY CONTAIN: CI 77491, CI 7749...",CI 77499 / IRON OXIDES,unresolved_residual,0.0,11458,5,Review optional colorants and may-contain context,pending
486,CRÈME COLORANTE : AQUA,CR ME COLORANTE,unresolved_residual,0.0,14318,1,Separate product description from ingredient text,pending
499,"[MAY CONTAIN/PEUT CONTENIR/+/-:MICA, TITANIUM ...","D C BLACK NO. 2 (CI 77266), CLEARLY QUICK TOP ...",unresolved_residual,0.0,14723,10,Review optional colorants and may-contain context,pending
500,"[MAY CONTAIN/PEUT CONTENIR/+/-:MICA, TITANIUM ...",D C RED NO. 34 CALCIUM LAKE (CI 15880),unresolved_residual,0.0,14748,8,Review optional colorants and may-contain context,pending
502,[MAY CONTAIN/PEUT CONTENIR/+/-:FERRIC AMMONIUM...,D C RED NO. 7 CALCIUM LAKE (CI 15850),unresolved_residual,0.0,14754,3,Review optional colorants and may-contain context,pending

In [28]:
print("Review actions:")
display(
    review_queue["recommended_action"]
    .value_counts()
    .rename_axis("action")
    .reset_index(name="rows")
)

print("\nReview rows by mapping method:")
display(
    review_queue.groupby("method", dropna=False)
    .size()
    .reset_index(name="rows")
    .sort_values("rows", ascending=False)
)

print("\nReview rows by canonical ingredient ID:")
display(
    review_queue.groupby("ingredient_id", dropna=False)
    .size()
    .reset_index(name="rows")
    .sort_values("rows", ascending=False)
    .head(20)
)

Review actions:

                                              action  rows
0  Review optional colorants and may-contain context    28
1  Separate manufacturer code from ingredient ide...    13
2  Separate product description from ingredient text    10
3  Verify ingredient splitting and each resulting...     9
4    Manual identification required; do not auto-map     8
5            Review context before accepting mapping     7
6  Verify canonical ingredient against a trusted ...     3

Review rows by mapping method:

                method  rows
7  unresolved_residual    30
0              cleaned    13
4        slash_variant     8
5                split     8
1                exact     7
2       paren_stripped     7
6           unresolved     3
3       slash_same_cas     2

Review rows by canonical ingredient ID:

    ingredient_id  rows
15           5225    10
47          31727     5
19          11405     2
22          11548     2
38          20582     2
48          33145     2
36          18978     2
45          28295     2
13           4459     2
4             407     1
9            2342     1
8            2291     1
7             842     1
6             435     1
12           4098     1
14           4691     1
11           3315     1
10           2493     1
17          11332     1
16           7575     1

In [29]:

from pathlib import Path
import pandas as pd

# Paths
BASE_DIR = Path("/content/drive/MyDrive/ingredia_backup/ingredia_data")
CLEANED_DIR = BASE_DIR / "cleaned"

INPUT_FILE = CLEANED_DIR / "ingredient_mapping_review_queue.csv"
OUTPUT_FILE = CLEANED_DIR / "ingredient_mapping_manual_review.csv"

# Load the existing review queue
review = pd.read_csv(INPUT_FILE)

# Add columns for explicit human review
review_columns = {
    "review_decision": "pending",
    "corrected_canonical_name": "",
    "presence_type": "unknown",
    "evidence_source": "",
    "review_notes": "",
    "reviewed_by": "",
    "reviewed_at": ""
}

for column, default_value in review_columns.items():
    if column not in review.columns:
        review[column] = default_value

# Keep the original data intact and sort by review priority
priority = {
    "Manual identification required; do not auto-map": 1,
    "Separate manufacturer code from ingredient ide...": 2,
    "Separate product description from ingredient text": 3,
    "Verify ingredient splitting and each resulting...": 4,
    "Review optional colorants and may-contain context": 5,
    "Review context before accepting mapping": 6,
    "Verify canonical ingredient against a trusted ...": 7
}

review["review_priority"] = (
    review["recommended_action"].map(priority).fillna(99)
)

review = review.sort_values(
    ["review_priority", "confidence", "raw_name"],
    ascending=[True, True, True]
).reset_index(drop=True)

CLEANED_DIR.mkdir(parents=True, exist_ok=True)
review.to_csv(OUTPUT_FILE, index=False)

print("Review worksheet created:", OUTPUT_FILE)
print("Rows:", len(review))
print("\nDecision status:")
print(review["review_decision"].value_counts(dropna=False))

print("\nPresence type should be one of:")
print([
    "confirmed",
    "may_contain",
    "label_metadata",
    "manufacturer_code",
    "unknown"
])

print("\nReview decision should be one of:")
print(["accepted", "corrected", "rejected", "unresolved", "pending"])

display(review.head(15))

Review worksheet created: /content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned/ingredient_mapping_manual_review.csv
Rows: 78

Decision status:
review_decision
pending    78
Name: count, dtype: int64

Presence type should be one of:
['confirmed', 'may_contain', 'label_metadata', 'manufacturer_code', 'unknown']

Review decision should be one of:
['accepted', 'corrected', 'rejected', 'unresolved', 'pending']

,raw_name,canonical_name,method,confidence,ingredient_id,part_index,recommended_action,review_status,review_decision,corrected_canonical_name,presence_type,evidence_source,review_notes,reviewed_by,reviewed_at,review_priority
0,1-NAPHTHOL. ACTIVATOR AQUA/WATER/EAU,ACTIVATOR AQUA/WATER/EAU,unresolved_residual,0.00,3315,2,Manual identification required; do not auto-map,pending,pending,,unknown,,,,,1.0
1,695126 41 INGREDIENTS : AQUA / WATER,695126 41 INGREDIENTS,unresolved_residual,0.00,2291,1,Manual identification required; do not auto-map,pending,pending,,unknown,,,,,1.0
2,737201 6 - INGREDIENTS : AQUA / WATER,737201 6 - INGREDIENTS,unresolved_residual,0.00,2342,1,Manual identification required; do not auto-map,pending,pending,,unknown,,,,,1.0
3,8855963-INGREDIENTS: AQUA/WATER,8855963-INGREDIENTS,unresolved_residual,0.00,2493,1,Manual identification required; do not auto-map,pending,pending,,unknown,,,,,1.0
4,AMMONIUM SULFATE. EMULSION RÉVÉLATRICE : AQUA,EMULSION R V LATRICE,unresolved_residual,0.00,17266,2,Manual identification required; do not auto-map,pending,pending,,unknown,,,,,1.0
5,ETIDRONIC ACID. BONDING TREATMENT AQUA/WATER/EAU,BONDING TREATMENT AQUA/WATER/EAU,unresolved_residual,0.00,7575,2,Manual identification required; do not auto-map,pending,pending,,unknown,,,,,1.0
6,INACTIVE INGREDIENTS GLYCERIN,INACTIVE INGREDIENTS,unresolved_residual,0.00,23627,1,Manual identification required; do not auto-map,pending,pending,,unknown,,,,,1.0
7,LZM ENTHALT: NATR UMFLUORID (1450 PPM F) INGRE...,"LZM ENTHALT, NATR UMFLUORID (1450 PPM F) INGRE...",unresolved_residual,0.00,26740,1,Manual identification required; do not auto-map,pending,pending,,unknown,,,,,1.0
8,COPPER GLUCONATE. FABRICADO Y EXPORTADO POR: J...,"FABRICADO Y EXPORTADO POR, JOHNSON HYDROXIDE",unresolved_residual,0.00,18753,2,Separate product description from ingredient text,pending,pending,,unknown,,,,,3.0
9,CRÈME COLORANTE : AQUA,CR ME COLORANTE,unresolved_residual,0.00,14318,1,Separate product description from ingredient text,pending,pending,,unknown,,,,,3.0
10,DUSCHGEL MIT VERWÖHNENDEM DUFT NACH MAGNOLIE. ...,DUSCHGEL MIT VERW HNENDEM DUFT NACH MAGNOLIE,unresolved_residual,0.00,16741,1,Separate product description from ingredient text,pending,pending,,unknown,,,,,3.0
11,NATURKOSMETIK OHNE KOMPROMISSE - MIT HOCHWERTI...,NATURKOSMETIK OHNE KOMPROMISSE - MIT HOCHWERTI...,unresolved_residual,0.00,29176,1,Separate product description from ingredient text,pending,pending,,unknown,,,,,3.0
12,WWW.NIVEAUSA.COM QUESTIONS? COMMENTS?1-800-227...,WWW.NIVEAUSA.COM QUESTIONS COMMENTS 1-800-227-...,unresolved_residual,0.00,44841,1,Separate product description from ingredient text,pending,pending,,unknown,,,,,3.0
13,COPPER GLUCONATE. FABRICADO Y EXPORTADO POR: J...,COPPER GLUCONATE,cleaned,0.85,14134,1,Separate product description from ingredient text,pending,pending,,unknown,,,,,3.0
14,CRÈME COLORANTE : AQUA,AQUA,cleaned,0.85,5225,2,Separate product description from ingredient text,pending,pending,,unknown,,,,,3.0

In [33]:

from pathlib import Path
import pandas as pd
import re

# ---------- Paths ----------
# Corrected to reference the correct Google Drive folder
DATA_DIR = Path("/content/drive/MyDrive/ingredia_backup/ingredia_data")
INCIDB_DIR = DATA_DIR / "incidb"

OUTPUT_DIR = Path(
    "/content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned"
)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

ingredients = pd.read_csv(INCIDB_DIR / "ingredients.csv", sep="|")
name_map = pd.read_csv(INCIDB_DIR / "ingredient_name_map.csv", sep="|")
products = pd.read_csv(INCIDB_DIR / "products.csv", sep="|")
product_ingredients = pd.read_csv(
    INCIDB_DIR / "product_ingredients.csv", sep="|"
)

# ---------- Normalize names for matching only ----------
def normalize_name(value):
    if pd.isna(value):
        return ""
    value = str(value).strip().upper()
    value = re.sub(r"\s+", " ", value)
    return value

# Keep all original ingredient fields and add a normalized search key.
ingredient_master = ingredients.copy()
ingredient_master["normalized_name"] = (
    ingredient_master["inci_name"].map(normalize_name)
)

# Do not silently remove records if a normalized name is duplicated.
ingredient_master["canonical_record_status"] = "source_record"

# Add provenance metadata.
ingredient_master["source_table"] = "INCIDB ingredients.csv"
ingredient_master["source_record_id"] = ingredient_master["ingredient_id"]

# ---------- Basic integrity checks ----------
assert "ingredient_id" in ingredient_master.columns
assert "inci_name" in ingredient_master.columns

print("Ingredient master rows:", len(ingredient_master))
print("Unique ingredient IDs:", ingredient_master["ingredient_id"].nunique())
print(
    "Empty ingredient names:",
    ingredient_master["normalized_name"].eq("").sum()
)
print(
    "Duplicate ingredient IDs:",
    ingredient_master["ingredient_id"].duplicated().sum()
)
print(
    "Duplicate normalized names:",
    ingredient_master["normalized_name"].duplicated(keep=False).sum()
)

# ---------- Export ----------
master_path = OUTPUT_DIR / "canonical_ingredient_master.csv"
ingredient_master.to_csv(master_path, index=False)

# Preserve original mappings in a separate table.
mapping_path = OUTPUT_DIR / "ingredient_alias_mapping_raw.csv"
name_map.to_csv(mapping_path, index=False)

print("\nSaved files:")
print(master_path)
print(mapping_path)

display(
    ingredient_master[
        [
            "ingredient_id",
            "inci_name",
            "normalized_name",
            "canonical_record_status",
            "source_table"
        ]
    ].head(10)
)

Ingredient master rows: 1123
Unique ingredient IDs: 1123
Empty ingredient names: 0
Duplicate ingredient IDs: 0
Duplicate normalized names: 0

Saved files:
/content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned/canonical_ingredient_master.csv
/content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned/ingredient_alias_mapping_raw.csv

,ingredient_id,inci_name,normalized_name,canonical_record_status,source_table
0,51,( /-),( /-),source_record,INCIDB ingredients.csv
1,203,(F.I.L B38252/3),(F.I.L B38252/3),source_record,INCIDB ingredients.csv
2,204,(F.I.L B48924/1),(F.I.L B48924/1),source_record,INCIDB ingredients.csv
3,347,"(F.I.L,Y70037597/1)","(F.I.L,Y70037597/1)",source_record,INCIDB ingredients.csv
4,407,(F.I.L.Z70042467/1),(F.I.L.Z70042467/1),source_record,INCIDB ingredients.csv
5,420,(F01),(F01),source_record,INCIDB ingredients.csv
6,435,(FIL B44107/1),(FIL B44107/1),source_record,INCIDB ingredients.csv
7,550,(SD ALCOHOL 39-C),(SD ALCOHOL 39-C),source_record,INCIDB ingredients.csv
8,803,"1,2-HEXANEDIOL","1,2-HEXANEDIOL",source_record,INCIDB ingredients.csv
9,841,1-METHYLHYDANTOIN-2-IMIDE,1-METHYLHYDANTOIN-2-IMIDE,source_record,INCIDB ingredients.csv

In [35]:

from pathlib import Path
import pandas as pd

DATA_DIR = Path("/content/drive/MyDrive/ingredia_backup/ingredia_data")
INCIDB_DIR = DATA_DIR / "incidb"
OUTPUT_DIR = Path(
    "/content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned"
)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Reload the original tables
ingredients = pd.read_csv(INCIDB_DIR / "ingredients.csv", sep="|")
products = pd.read_csv(INCIDB_DIR / "products.csv", sep="|")
product_ingredients = pd.read_csv(
    INCIDB_DIR / "product_ingredients.csv", sep="|"
)
name_map = pd.read_csv(
    INCIDB_DIR / "ingredient_name_map.csv", sep="|"
)

# Check required relationship columns before exporting
required_columns = {
    "ingredients": (ingredients, ["ingredient_id"]),
    "products": (products, ["product_id"]),
    "product_ingredients": (
        product_ingredients, ["product_id", "ingredient_id"]
    ),
    "name_map": (name_map, ["ingredient_id"])
}

for table_name, (df, required) in required_columns.items():
    missing = [col for col in required if col not in df.columns]
    if missing:
        print(f"{table_name} columns:", df.columns.tolist())
        raise ValueError(
            f"{table_name} is missing required columns: {missing}"
        )

# Validate foreign-key relationships
valid_ingredient_ids = set(ingredients["ingredient_id"].dropna())
valid_product_ids = set(products["product_id"].dropna())

invalid_product_ingredient_rows = product_ingredients[
    ~product_ingredients["ingredient_id"].isin(valid_ingredient_ids)
    | ~product_ingredients["product_id"].isin(valid_product_ids)
]

invalid_alias_rows = name_map[
    ~name_map["ingredient_id"].isin(valid_ingredient_ids)
]

print("Original ingredient rows:", len(ingredients))
print("Original product rows:", len(products))
print("Product-ingredient relationship rows:", len(product_ingredients))
print("Raw name mapping rows:", len(name_map))
print("Invalid product-ingredient relationships:",
      len(invalid_product_ingredient_rows))
print("Invalid alias-to-ingredient references:", len(invalid_alias_rows))

# Export API-ready copies; source tables remain unchanged.
exports = {
    "api_ingredients.csv": ingredients,
    "api_products.csv": products,
    "api_product_ingredients.csv": product_ingredients,
    "api_ingredient_aliases.csv": name_map
}

for filename, df in exports.items():
    output_path = OUTPUT_DIR / filename
    df.to_csv(output_path, index=False)
    print("Saved:", output_path)

# Report relationships and potential duplicate associations
duplicate_links = product_ingredients.duplicated(
    subset=["product_id", "ingredient_id"]
).sum()

print("\nDuplicate product-ingredient pairs:", duplicate_links)
print("\nIngredient columns:", ingredients.columns.tolist())
print("Product columns:", products.columns.tolist())
print("Relationship columns:", product_ingredients.columns.tolist())
print("Alias columns:", name_map.columns.tolist())

Original ingredient rows: 1123
Original product rows: 200
Product-ingredient relationship rows: 4089
Raw name mapping rows: 1467
Invalid product-ingredient relationships: 0
Invalid alias-to-ingredient references: 0
Saved: /content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned/api_ingredients.csv
Saved: /content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned/api_products.csv
Saved: /content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned/api_product_ingredients.csv
Saved: /content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned/api_ingredient_aliases.csv

Duplicate product-ingredient pairs: 0

Ingredient columns: ['ingredient_id', 'inci_name', 'cosing_matched', 'cosing_ref_no', 'cas_number', 'ec_number', 'functions', 'chemical_description', 'cosing_restriction', 'cosing_update_date', 'annex_ii', 'annex_iii', 'annex_iv', 'annex_v', 'annex_vi', 'is_common_allergen', 'allergen_source', 'comedogenic_rating', 'is_fungal_acne_trigger', 'rating_source']
Product columns: ['product_id', 'brand_id', 'barcode_ean', 'name', 'obf_categories_tags', 'raw_ingredient_text', 'created_at']
Relationship columns: ['product_id', 'ingredient_id', 'position_index', 'concentration_percentage']
Alias columns: ['raw_name', 'canonical_name', 'method', 'confidence', 'ingredient_id', 'part_index', 'split_rule']

In [36]:

import sqlite3
import pandas as pd
from pathlib import Path

# ---------- Paths ----------
DATA_DIR = Path(
    "/content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned"
)
DB_PATH = DATA_DIR / "ingredia.db"

csv_tables = {
    "ingredients": "api_ingredients.csv",
    "products": "api_products.csv",
    "product_ingredients": "api_product_ingredients.csv",
    "ingredient_aliases": "api_ingredient_aliases.csv",
}

# ---------- Create database ----------
if DB_PATH.exists():
    DB_PATH.unlink()  # Rebuild only this generated database file

conn = sqlite3.connect(DB_PATH)

try:
    expected_counts = {}

    for table_name, filename in csv_tables.items():
        csv_path = DATA_DIR / filename
        df = pd.read_csv(csv_path)

        df.to_sql(
            table_name,
            conn,
            if_exists="replace",
            index=False
        )

        expected_counts[table_name] = len(df)

    # Add indexes to speed up common searches and joins.
    conn.executescript("""
        CREATE INDEX idx_ingredients_name
        ON ingredients(inci_name);

        CREATE INDEX idx_products_name
        ON products(name);

        CREATE INDEX idx_products_barcode
        ON products(barcode_ean);

        CREATE INDEX idx_product_ingredients_product
        ON product_ingredients(product_id);

        CREATE INDEX idx_product_ingredients_ingredient
        ON product_ingredients(ingredient_id);

        CREATE INDEX idx_aliases_ingredient
        ON ingredient_aliases(ingredient_id);
    """)

    conn.commit()

    # ---------- Verify database ----------
    print("Database:", DB_PATH)
    print("\nRow-count verification:")

    for table_name, expected in expected_counts.items():
        actual = conn.execute(
            f"SELECT COUNT(*) FROM {table_name}"
        ).fetchone()[0]

        print(f"{table_name}: {actual} rows (CSV: {expected})")
        assert actual == expected, f"Row count mismatch: {table_name}"

    # Test a sample product-to-ingredient join.
    sample = pd.read_sql_query("""
        SELECT
            p.product_id,
            p.name AS product_name,
            i.ingredient_id,
            i.inci_name,
            pi.position_index
        FROM products p
        JOIN product_ingredients pi
            ON p.product_id = pi.product_id
        JOIN ingredients i
            ON pi.ingredient_id = i.ingredient_id
        ORDER BY p.product_id, pi.position_index
        LIMIT 10
    """, conn)

    print("\nSample product-ingredient join:")
    display(sample)

    print("\nDatabase verification passed.")

finally:
    conn.close()

Database: /content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned/ingredia.db

Row-count verification:
ingredients: 1123 rows (CSV: 1123)
products: 200 rows (CSV: 200)
product_ingredients: 4089 rows (CSV: 4089)
ingredient_aliases: 1467 rows (CSV: 1467)

Sample product-ingredient join:

,product_id,product_name,ingredient_id,inci_name,position_index
0,498,Fixation extra forte,8993,CALCIUM/ZINC PVM/MA COPOLYMER,1
1,498,Fixation extra forte,31648,PARAFFINUM LIQUIDUM,2
2,498,Fixation extra forte,33128,PETROLATUM,3
3,498,Fixation extra forte,9961,CELLULOSE GUM,4
4,498,Fixation extra forte,38472,SILICA,5
5,580,Shampooing expert anti pelliculaire Citrus,5225,AQUA,1
6,580,Shampooing expert anti pelliculaire Citrus,39729,SODIUM LAURETH SULFATE,2
7,580,Shampooing expert anti pelliculaire Citrus,39264,SODIUM CHLORIDE,3
8,580,Shampooing expert anti pelliculaire Citrus,12864,COCAMIDOPROPYL BETAINE,4
9,580,Shampooing expert anti pelliculaire Citrus,25425,LAURETH-2,5

Database verification passed.

In [37]:

!pip -q install fastapi uvicorn

In [38]:

from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/ingredia_backup/ingredia_data"
)
CLEANED_DIR = PROJECT_DIR / "cleaned"
DB_PATH = CLEANED_DIR / "ingredia.db"

MAIN_PY = PROJECT_DIR / "main.py"

api_code = r'''
import os
import sqlite3
from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, Query

DB_PATH = Path(
    os.environ.get(
        "INGREDIA_DB_PATH",
        "/content/drive/MyDrive/ingredia_backup/ingredia_data/cleaned/ingredia.db"
    )
)

app = FastAPI(
    title="Ingredia API",
    description=(
        "Ingredient and cosmetic product information API. "
        "Source-reported information is not a universal safety verdict."
    ),
    version="0.1.0"
)


def get_connection():
    if not DB_PATH.exists():
        raise RuntimeError(f"Database not found: {DB_PATH}")

    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA query_only = ON")
    return conn


def rows_to_dicts(rows):
    return [dict(row) for row in rows]


@app.get("/")
def root():
    return {
        "name": "Ingredia API",
        "status": "running",
        "docs": "/docs"
    }


@app.get("/health")
def health():
    try:
        with get_connection() as conn:
            count = conn.execute(
                "SELECT COUNT(*) FROM ingredients"
            ).fetchone()[0]
        return {"status": "healthy", "ingredient_records": count}
    except Exception:
        raise HTTPException(
            status_code=503,
            detail="Database is unavailable or not initialized"
        )


@app.get("/ingredients")
def search_ingredients(
    search: Optional[str] = Query(default=None, max_length=100),
    limit: int = Query(default=20, ge=1, le=100),
    offset: int = Query(default=0, ge=0)
):
    with get_connection() as conn:
        if search and search.strip():
            term = "%" + search.strip() + "%"
            rows = conn.execute(
                """
                SELECT ingredient_id, inci_name, functions,
                       chemical_description, cosing_matched,
                       cosing_ref_no, cas_number, ec_number
                FROM ingredients
                WHERE inci_name LIKE ?
                ORDER BY inci_name
                LIMIT ? OFFSET ?
                """,
                (term, limit, offset)
            ).fetchall()
        else:
            rows = conn.execute(
                """
                SELECT ingredient_id, inci_name, functions,
                       chemical_description, cosing_matched,
                       cosing_ref_no, cas_number, ec_number
                FROM ingredients
                ORDER BY inci_name
                LIMIT ? OFFSET ?
                """,
                (limit, offset)
            ).fetchall()

    return {
        "count": len(rows),
        "limit": limit,
        "offset": offset,
        "results": rows_to_dicts(rows)
    }


@app.get("/ingredients/{ingredient_id}")
def get_ingredient(ingredient_id: int):
    with get_connection() as conn:
        row = conn.execute(
            "SELECT * FROM ingredients WHERE ingredient_id = ?",
            (ingredient_id,)
        ).fetchone()

    if row is None:
        raise HTTPException(status_code=404, detail="Ingredient not found")

    return dict(row)


@app.get("/products")
def search_products(
    search: Optional[str] = Query(default=None, max_length=150),
    barcode: Optional[str] = Query(default=None, max_length=50),
    limit: int = Query(default=20, ge=1, le=100),
    offset: int = Query(default=0, ge=0)
):
    clauses = []
    params = []

    if search and search.strip():
        clauses.append("name LIKE ?")
        params.append("%" + search.strip() + "%")

    if barcode and barcode.strip():
        clauses.append("barcode_ean = ?")
        params.append(barcode.strip())

    sql = "SELECT * FROM products"
    if clauses:
        sql += " WHERE " + " AND ".join(clauses)

    sql += " ORDER BY name LIMIT ? OFFSET ?"
    params.extend([limit, offset])

    with get_connection() as conn:
        rows = conn.execute(sql, params).fetchall()

    return {
        "count": len(rows),
        "limit": limit,
        "offset": offset,
        "results": rows_to_dicts(rows)
    }


@app.get("/products/{product_id}/ingredients")
def get_product_ingredients(product_id: int):
    with get_connection() as conn:
        product = conn.execute(
            "SELECT * FROM products WHERE product_id = ?",
            (product_id,)
        ).fetchone()

        if product is None:
            raise HTTPException(
                status_code=404, detail="Product not found"
            )

        rows = conn.execute(
            """
            SELECT i.*, pi.position_index,
                   pi.concentration_percentage
            FROM product_ingredients pi
            JOIN ingredients i
              ON i.ingredient_id = pi.ingredient_id
            WHERE pi.product_id = ?
            ORDER BY pi.position_index
            """,
            (product_id,)
        ).fetchall()

    return {
        "product": dict(product),
        "ingredient_count": len(rows),
        "ingredients": rows_to_dicts(rows)
    }
'''

MAIN_PY.write_text(api_code, encoding="utf-8")

print("Created:", MAIN_PY)
print("Database exists:", DB_PATH.exists())

Created: /content/drive/MyDrive/ingredia_backup/ingredia_data/main.py
Database exists: True

In [39]:

import subprocess
import sys
import time
import urllib.request
import json

# Stop any earlier server started from this notebook, if applicable.
if "api_process" in globals() and api_process.poll() is None:
    api_process.terminate()
    api_process.wait(timeout=5)

api_process = subprocess.Popen(
    [
        sys.executable, "-m", "uvicorn",
        "main:app",
        "--app-dir", str(PROJECT_DIR),
        "--host", "127.0.0.1",
        "--port", "8000"
    ],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)

time.sleep(3)

def check_endpoint(url):
    try:
        with urllib.request.urlopen(url, timeout=5) as response:
            payload = json.loads(response.read().decode("utf-8"))
            print(f"\n{url}")
            print(json.dumps(payload, indent=2)[:1800])
    except Exception as exc:
        print(f"\nRequest failed: {url}")
        print(repr(exc))

check_endpoint("http://127.0.0.1:8000/")
check_endpoint("http://127.0.0.1:8000/health")
check_endpoint("http://127.0.0.1:8000/ingredients?search=AQUA")
check_endpoint("http://127.0.0.1:8000/products/580/ingredients")

Request failed: http://127.0.0.1:8000/
URLError(ConnectionRefusedError(111, 'Connection refused'))

Request failed: http://127.0.0.1:8000/health
URLError(ConnectionRefusedError(111, 'Connection refused'))

Request failed: http://127.0.0.1:8000/ingredients?search=AQUA
URLError(ConnectionRefusedError(111, 'Connection refused'))

Request failed: http://127.0.0.1:8000/products/580/ingredients
URLError(ConnectionRefusedError(111, 'Connection refused'))

In [40]:

import sys
import subprocess
import importlib.util
from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/ingredia_backup/ingredia_data"
)
DB_PATH = PROJECT_DIR / "cleaned" / "ingredia.db"
MAIN_PY = PROJECT_DIR / "main.py"
LOG_PATH = PROJECT_DIR / "uvicorn_debug.log"

print("main.py exists:", MAIN_PY.exists())
print("Database exists:", DB_PATH.exists())
print("FastAPI installed:", importlib.util.find_spec("fastapi") is not None)
print("Uvicorn installed:", importlib.util.find_spec("uvicorn") is not None)

if not MAIN_PY.exists():
    raise FileNotFoundError(f"API file not found: {MAIN_PY}")

# Test whether the application can be imported.
print("\n--- Testing API import ---")
import_test = subprocess.run(
    [
        sys.executable, "-c",
        "import sys; "
        f"sys.path.insert(0, {str(PROJECT_DIR)!r}); "
        "import main; print('API import successful')"
    ],
    capture_output=True,
    text=True,
    timeout=30
)

print(import_test.stdout)
if import_test.stderr:
    print(import_test.stderr)

if import_test.returncode != 0:
    print("Import failed. Fix the error above before starting Uvicorn.")
else:
    # Start Uvicorn with its logs saved instead of discarded.
    with open(LOG_PATH, "w", encoding="utf-8") as log_file:
        debug_process = subprocess.Popen(
            [
                sys.executable, "-m", "uvicorn",
                "main:app",
                "--app-dir", str(PROJECT_DIR),
                "--host", "127.0.0.1",
                "--port", "8000"
            ],
            stdout=log_file,
            stderr=subprocess.STDOUT
        )

    import time
    time.sleep(3)

    print("\nServer process running:", debug_process.poll() is None)
    print("\n--- Uvicorn log ---")
    print(LOG_PATH.read_text(encoding="utf-8"))

    if debug_process.poll() is None:
        print("Server appears to have started. Test the endpoints next.")
    else:
        print("Server exited. Use the log above to identify the cause.")

main.py exists: True
Database exists: True
FastAPI installed: True
Uvicorn installed: True

--- Testing API import ---
API import successful


Server process running: False

--- Uvicorn log ---
INFO:     Started server process [15057]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

Server exited. Use the log above to identify the cause.

In [41]:

import subprocess
import sys
import time
import urllib.request
import json
from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/ingredia_backup/ingredia_data"
)

# Start Uvicorn on an unused port
api_process = subprocess.Popen(
    [
        sys.executable, "-m", "uvicorn",
        "main:app",
        "--app-dir", str(PROJECT_DIR),
        "--host", "127.0.0.1",
        "--port", "8001"
    ],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)

time.sleep(3)

print("Process running:", api_process.poll() is None)

def test_api(path):
    url = "http://127.0.0.1:8001" + path
    try:
        with urllib.request.urlopen(url, timeout=10) as response:
            data = json.loads(response.read().decode("utf-8"))
            print(f"\nPASS {path} (HTTP {response.status})")
            print(json.dumps(data, indent=2)[:1000])
    except Exception as exc:
        print(f"\nFAIL {path}: {exc}")

test_api("/")
test_api("/health")
test_api("/ingredients?search=AQUA")
test_api("/products/580/ingredients")

Process running: True

PASS / (HTTP 200)
{
  "name": "Ingredia API",
  "status": "running",
  "docs": "/docs"
}

PASS /health (HTTP 200)
{
  "status": "healthy",
  "ingredient_records": 1123
}

PASS /ingredients?search=AQUA (HTTP 200)
{
  "count": 9,
  "limit": 20,
  "offset": 0,
  "results": [
    {
      "ingredient_id": 3315,
      "inci_name": "ACTIVATOR AQUA/WATER/EAU",
      "functions": null,
      "chemical_description": null,
      "cosing_matched": 0,
      "cosing_ref_no": null,
      "cas_number": null,
      "ec_number": null
    },
    {
      "ingredient_id": 5123,
      "inci_name": "APHANIZOMENON FLOS-AQUAE EXTRACT",
      "functions": null,
      "chemical_description": null,
      "cosing_matched": 0,
      "cosing_ref_no": null,
      "cas_number": null,
      "ec_number": null
    },
    {
      "ingredient_id": 5225,
      "inci_name": "AQUA",
      "functions": "SOLVENT",
      "chemical_description": "Water",
      "cosing_matched": 1,
      "cosing_ref_no": 31959.0,
      "cas_number": "7732-18-5",
      "ec_number": "231-791-2"
    },
    {
      "ingredient_id": 5328,
      "inci_name": "AQUA VATER)",
      "functions": null,
      "chemical_description": null,
      "cosing_matched": 0,


PASS /products/580/ingredients (HTTP 200)
{
  "product": {
    "product_id": 580,
    "brand_id": 529.0,
    "barcode_ean": 3140100336979,
    "name": "Shampooing expert anti pelliculaire Citrus",
    "obf_categories_tags": "en:hair;en:shampoos;en:anti-dandruff-shampoos",
    "raw_ingredient_text": "AQUA/WATER/EAU, SODIUM LAURETH SULFATE, SODIUM CHLORIDE, COCAMIDOPROPYL BETAINE, LAURETH-2, PEG-40 HYDROGENATED CASTOR OIL, PARFUM (FRAGRANCE), ZINC PYRITHIONE, ACRYLATES COPOLYMER, GUAR HYDROXYPROPYLTRIMONIUM CHLORIDE, DMDM HYDANTOIN, QUATERNIUM-80, PROPYLENE GLYCOL, CITRUS LIMON (LEMON) PEEL OIL, LIMONENE, SODIUM POLYNAPHTHALENESULFONATE, PANTHENOL, CITRUS AURANTIFOLIA (LIME) SEED OIL, CITRAL, PANTOLACTONE, YELLOW 5 (CI 19140), GREEN 5 (CI 61570), LINALOOL, CITRIC ACID, TRIETHANOLAMINE, (F01)",
    "created_at": "2026-10-10 10:34:34"
  },
  "ingredient_count": 26,
  "ingredients": [
    {
      "ingredient_id": 5225,
      "inci_name": "AQUA",
      "cosing_matched": 1,
      "cosing_ref_no": 31959.0,
      "cas_number": "7732-18

In [42]:

from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/ingredia_backup/ingredia_data"
)
MAIN_PY = PROJECT_DIR / "main.py"

alias_search_code = r'''

@app.get("/ingredient-search")
def ingredient_search(
    search: str = Query(..., min_length=1, max_length=100),
    limit: int = Query(default=20, ge=1, le=100),
    offset: int = Query(default=0, ge=0)
):
    term = search.strip()
    if not term:
        raise HTTPException(status_code=422, detail="Search cannot be blank")

    pattern = "%" + term + "%"
    prefix = term + "%"

    with get_connection() as conn:
        # Discover alias columns from the actual database schema.
        alias_columns = [
            row["name"]
            for row in conn.execute(
                "PRAGMA table_info(ingredient_aliases)"
            ).fetchall()
        ]

        if "ingredient_id" not in alias_columns:
            raise HTTPException(
                status_code=500,
                detail="Alias table has no ingredient_id column"
            )

        possible_name_columns = [
            "raw_name", "canonical_name", "inci_name",
            "alias", "name", "normalized_name"
        ]
        name_columns = [
            col for col in possible_name_columns
            if col in alias_columns
        ]

        alias_ids = set()

        if name_columns:
            conditions = " OR ".join(
                f'CAST("{col}" AS TEXT) LIKE ?'
                for col in name_columns
            )
            params = [pattern] * len(name_columns)

            rows = conn.execute(
                f"""
                SELECT DISTINCT ingredient_id
                FROM ingredient_aliases
                WHERE {conditions}
                """,
                params
            ).fetchall()

            alias_ids = {
                row["ingredient_id"] for row in rows
                if row["ingredient_id"] is not None
            }

        # Search direct INCI names, plus ingredients reached through aliases.
        direct_rows = conn.execute(
            """
            SELECT ingredient_id, inci_name, functions,
                   chemical_description, cosing_matched,
                   cosing_ref_no, cas_number, ec_number
            FROM ingredients
            WHERE inci_name LIKE ?
            """,
            (pattern,)
        ).fetchall()

        candidates = {
            row["ingredient_id"]: dict(row)
            for row in direct_rows
        }

        if alias_ids:
            valid_ids = [
                ingredient_id for ingredient_id in alias_ids
            ]
            placeholders = ",".join("?" for _ in valid_ids)

            alias_rows = conn.execute(
                f"""
                SELECT ingredient_id, inci_name, functions,
                       chemical_description, cosing_matched,
                       cosing_ref_no, cas_number, ec_number
                FROM ingredients
                WHERE ingredient_id IN ({placeholders})
                """,
                valid_ids
            ).fetchall()

            for row in alias_rows:
                candidates[row["ingredient_id"]] = dict(row)

        # Rank exact name matches, then prefix matches, then other matches.
        def rank(item):
            name = str(item["inci_name"] or "").casefold()
            query = term.casefold()

            if name == query:
                match_rank = 0
            elif name.startswith(query):
                match_rank = 1
            elif item["ingredient_id"] in alias_ids:
                match_rank = 2
            else:
                match_rank = 3

            return (match_rank, name)

        results = sorted(candidates.values(), key=rank)
        total = len(results)
        page = results[offset:offset + limit]

    return {
        "query": term,
        "count": len(page),
        "total_matches": total,
        "limit": limit,
        "offset": offset,
        "results": page,
        "note": (
            "Alias matches are search suggestions, not confirmation "
            "that the raw label text is a verified synonym."
        )
    }
'''

# Avoid accidentally adding the same endpoint twice.
current_code = MAIN_PY.read_text(encoding="utf-8")

if '@app.get("/ingredient-search")' in current_code:
    print("The alias-aware endpoint already exists; no changes made.")
else:
    with MAIN_PY.open("a", encoding="utf-8") as f:
        f.write("\n" + alias_search_code + "\n")
    print("Added /ingredient-search to:", MAIN_PY)

Added /ingredient-search to: /content/drive/MyDrive/ingredia_backup/ingredia_data/main.py

In [43]:

import subprocess
import sys
import time
import urllib.request
import urllib.parse
import json

if "api_process" in globals() and api_process.poll() is None:
    api_process.terminate()
    api_process.wait(timeout=10)

api_process = subprocess.Popen(
    [
        sys.executable, "-m", "uvicorn",
        "main:app",
        "--app-dir", str(PROJECT_DIR),
        "--host", "127.0.0.1",
        "--port", "8001"
    ],
    stdout=subprocess.DEVNULL,
    stderr=subprocess.DEVNULL
)

time.sleep(3)

def test_search(term):
    query = urllib.parse.urlencode({"search": term})
    url = f"http://127.0.0.1:8001/ingredient-search?{query}"

    try:
        with urllib.request.urlopen(url, timeout=10) as response:
            data = json.loads(response.read().decode("utf-8"))
            print(f"\nSearch: {term} | HTTP {response.status}")
            print("Total matches:", data.get("total_matches"))
            for item in data.get("results", [])[:8]:
                print(
                    item["ingredient_id"],
                    item["inci_name"]
                )
    except Exception as exc:
        print(f"FAILED: {term} — {exc}")

print("Server running:", api_process.poll() is None)
test_search("AQUA")
test_search("WATER")
test_search("GLYCERIN")

Server running: True
FAILED: AQUA — <urlopen error [Errno 111] Connection refused>
FAILED: WATER — <urlopen error [Errno 111] Connection refused>
FAILED: GLYCERIN — <urlopen error [Errno 111] Connection refused>

In [44]:

import subprocess
import sys
import time
import urllib.request
from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/ingredia_backup/ingredia_data"
)
LOG_PATH = PROJECT_DIR / "uvicorn_8002.log"

# Check that the updated application imports.
check = subprocess.run(
    [
        sys.executable, "-c",
        f"import sys; sys.path.insert(0, {str(PROJECT_DIR)!r}); "
        "import main; print('Import successful')"
    ],
    capture_output=True,
    text=True,
    timeout=30
)

print("IMPORT TEST:")
print(check.stdout)
if check.stderr:
    print(check.stderr)

if check.returncode != 0:
    raise RuntimeError("Fix the import error shown above first.")

# Start on a different port and preserve all logs.
with open(LOG_PATH, "w", encoding="utf-8") as log:
    debug_api_process = subprocess.Popen(
        [
            sys.executable, "-m", "uvicorn",
            "main:app",
            "--app-dir", str(PROJECT_DIR),
            "--host", "127.0.0.1",
            "--port", "8002"
        ],
        stdout=log,
        stderr=subprocess.STDOUT
    )

time.sleep(4)

print("\nPROCESS EXIT CODE:", debug_api_process.poll())
print("\nSTARTUP LOG:")
print(LOG_PATH.read_text(encoding="utf-8"))

if debug_api_process.poll() is None:
    try:
        with urllib.request.urlopen(
            "http://127.0.0.1:8002/health", timeout=5
        ) as response:
            print("\nHEALTH CHECK:", response.status)
            print(response.read().decode("utf-8"))
    except Exception as exc:
        print("\nHealth request failed:", repr(exc))

IMPORT TEST:
Import successful


PROCESS EXIT CODE: None

STARTUP LOG:
INFO:     Started server process [16111]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8002 (Press CTRL+C to quit)


HEALTH CHECK: 200
{"status":"healthy","ingredient_records":1123}

In [45]:

import urllib.parse
import json
import urllib.request

url = (
    "http://127.0.0.1:8002/ingredient-search?"
    + urllib.parse.urlencode({"search": "AQUA"})
)

try:
    with urllib.request.urlopen(url, timeout=10) as response:
        result = json.loads(response.read().decode("utf-8"))
        print("HTTP status:", response.status)
        print("Total matches:", result.get("total_matches"))
        for item in result.get("results", [])[:10]:
            print(item["ingredient_id"], item["inci_name"])
except Exception as exc:
    print("Search failed:", repr(exc))

HTTP status: 200
Total matches: 33
5225 AQUA
5328 AQUA VATER)
842 1-NAPHTHOL
2291 695126 41 INGREDIENTS
2342 737201 6 - INGREDIENTS
2493 8855963-INGREDIENTS
3315 ACTIVATOR AQUA/WATER/EAU
4098 ALOE BARBADENSIS LEAF JUICE
4691 AMMONIUM SULFATE
5123 APHANIZOMENON FLOS-AQUAE EXTRACT